/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.routines;


import com.kenvix.bookmgr.orm.DefaultSchema;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookBorrowUnreturnedNum extends AbstractRoutine<Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>book_borrow_unreturned_num.RETURN_VALUE</code>.
     */
    public static final Parameter<Integer> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>book_borrow_unreturned_num.borrower_uid</code>.
     */
    public static final Parameter<Long> BORROWER_UID = Internal.createParameter("borrower_uid", SQLDataType.BIGINT, false, false);

    /**
     * Create a new routine call instance
     */
    public BookBorrowUnreturnedNum() {
        super("book_borrow_unreturned_num", DefaultSchema.DEFAULT_SCHEMA, SQLDataType.INTEGER);

        setReturnParameter(RETURN_VALUE);
        addInParameter(BORROWER_UID);
    }

    /**
     * Set the <code>borrower_uid</code> parameter IN value to the routine
     */
    public void setBorrowerUid(Long value) {
        setValue(BORROWER_UID, value);
    }

    /**
     * Set the <code>borrower_uid</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public BookBorrowUnreturnedNum setBorrowerUid(Field<Long> field) {
        setField(BORROWER_UID, field);
        return this;
    }
}
