/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.routines;


import com.kenvix.bookmgr.orm.DefaultSchema;

import javax.annotation.processing.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaiseError extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -1322614809;

    /**
     * The parameter <code>raise_error.error_message</code>.
     */
    public static final Parameter<String> ERROR_MESSAGE = Internal.createParameter("error_message", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * The parameter <code>raise_error.error_id</code>.
     */
    public static final Parameter<Short> ERROR_ID = Internal.createParameter("error_id", org.jooq.impl.SQLDataType.SMALLINT, false, false);

    /**
     * Create a new routine call instance
     */
    public RaiseError() {
        super("raise_error", DefaultSchema.DEFAULT_SCHEMA);

        addInParameter(ERROR_MESSAGE);
        addInParameter(ERROR_ID);
    }

    /**
     * Set the <code>error_message</code> parameter IN value to the routine
     */
    public void setErrorMessage(String value) {
        setValue(ERROR_MESSAGE, value);
    }

    /**
     * Set the <code>error_id</code> parameter IN value to the routine
     */
    public void setErrorId(Short value) {
        setValue(ERROR_ID, value);
    }
}
