/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.routines;


import com.kenvix.bookmgr.orm.DefaultSchema;

import javax.annotation.processing.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDelete extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>user_delete.uid_v</code>.
     */
    public static final Parameter<Long> UID_V = Internal.createParameter("uid_v", SQLDataType.BIGINT, false, false);

    /**
     * Create a new routine call instance
     */
    public UserDelete() {
        super("user_delete", DefaultSchema.DEFAULT_SCHEMA);

        addInParameter(UID_V);
    }

    /**
     * Set the <code>uid_v</code> parameter IN value to the routine
     */
    public void setUidV(Long value) {
        setValue(UID_V, value);
    }
}
