/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables;


import com.kenvix.bookmgr.orm.DefaultSchema;
import com.kenvix.bookmgr.orm.tables.records.LogUserLoginForAdminRecord;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LogUserLoginForAdmin extends TableImpl<LogUserLoginForAdminRecord> {

    private static final long serialVersionUID = -292771350;

    /**
     * The reference instance of <code>log_user_login_for_admin</code>
     */
    public static final LogUserLoginForAdmin LOG_USER_LOGIN_FOR_ADMIN = new LogUserLoginForAdmin();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LogUserLoginForAdminRecord> getRecordType() {
        return LogUserLoginForAdminRecord.class;
    }

    /**
     * The column <code>log_user_login_for_admin.created_at</code>. 创建时间
     */
    public final TableField<LogUserLoginForAdminRecord, Timestamp> CREATED_AT = createField(DSL.name("created_at"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0000-00-00 00:00:00", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>log_user_login_for_admin.access_level</code>. 访问级别
     */
    public final TableField<LogUserLoginForAdminRecord, Byte> ACCESS_LEVEL = createField(DSL.name("access_level"), org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.TINYINT)), this, "访问级别");

    /**
     * The column <code>log_user_login_for_admin.real_name</code>. 真实姓名
     */
    public final TableField<LogUserLoginForAdminRecord, String> REAL_NAME = createField(DSL.name("real_name"), org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "真实姓名");

    /**
     * The column <code>log_user_login_for_admin.email</code>. 电子邮箱
     */
    public final TableField<LogUserLoginForAdminRecord, String> EMAIL = createField(DSL.name("email"), org.jooq.impl.SQLDataType.VARCHAR(60).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "电子邮箱");

    /**
     * The column <code>log_user_login_for_admin.serial_id</code>. 工号/序列号
     */
    public final TableField<LogUserLoginForAdminRecord, String> SERIAL_ID = createField(DSL.name("serial_id"), org.jooq.impl.SQLDataType.VARCHAR(15).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "工号/序列号");

    /**
     * The column <code>log_user_login_for_admin.uid</code>. 用户UID
     */
    public final TableField<LogUserLoginForAdminRecord, Long> UID = createField(DSL.name("uid"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "用户UID");

    /**
     * The column <code>log_user_login_for_admin.ip</code>. 登录IP
     */
    public final TableField<LogUserLoginForAdminRecord, String> IP = createField(DSL.name("ip"), org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "登录IP");

    /**
     * The column <code>log_user_login_for_admin.time</code>. 登录时间
     */
    public final TableField<LogUserLoginForAdminRecord, Timestamp> TIME = createField(DSL.name("time"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "登录时间");

    /**
     * The column <code>log_user_login_for_admin.useragent</code>. 用户代理
     */
    public final TableField<LogUserLoginForAdminRecord, String> USERAGENT = createField(DSL.name("useragent"), org.jooq.impl.SQLDataType.CLOB, this, "用户代理");

    /**
     * Create a <code>log_user_login_for_admin</code> table reference
     */
    public LogUserLoginForAdmin() {
        this(DSL.name("log_user_login_for_admin"), null);
    }

    /**
     * Create an aliased <code>log_user_login_for_admin</code> table reference
     */
    public LogUserLoginForAdmin(String alias) {
        this(DSL.name(alias), LOG_USER_LOGIN_FOR_ADMIN);
    }

    /**
     * Create an aliased <code>log_user_login_for_admin</code> table reference
     */
    public LogUserLoginForAdmin(Name alias) {
        this(alias, LOG_USER_LOGIN_FOR_ADMIN);
    }

    private LogUserLoginForAdmin(Name alias, Table<LogUserLoginForAdminRecord> aliased) {
        this(alias, aliased, null);
    }

    private LogUserLoginForAdmin(Name alias, Table<LogUserLoginForAdminRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("VIEW"), TableOptions.view("create view `log_user_login_for_admin` as select `book`.`user`.`created_at` AS `created_at`,`book`.`user`.`access_level` AS `access_level`,`book`.`user`.`real_name` AS `real_name`,`book`.`user`.`email` AS `email`,`book`.`user`.`serial_id` AS `serial_id`,`book`.`user`.`uid` AS `uid`,`book`.`log_user_login`.`ip` AS `ip`,`book`.`log_user_login`.`time` AS `time`,`book`.`log_user_login`.`useragent` AS `useragent` from (`book`.`log_user_login` join `book`.`user` on((`book`.`log_user_login`.`uid` = `book`.`user`.`uid`)))"));
    }

    public <O extends Record> LogUserLoginForAdmin(Table<O> child, ForeignKey<O, LogUserLoginForAdminRecord> key) {
        super(child, key, LOG_USER_LOGIN_FOR_ADMIN);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public LogUserLoginForAdmin as(String alias) {
        return new LogUserLoginForAdmin(DSL.name(alias), this);
    }

    @Override
    public LogUserLoginForAdmin as(Name alias) {
        return new LogUserLoginForAdmin(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public LogUserLoginForAdmin rename(String name) {
        return new LogUserLoginForAdmin(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LogUserLoginForAdmin rename(Name name) {
        return new LogUserLoginForAdmin(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Timestamp, Byte, String, String, String, Long, String, Timestamp, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
