/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm;


import com.kenvix.bookmgr.orm.tables.Author;
import com.kenvix.bookmgr.orm.tables.Book;
import com.kenvix.bookmgr.orm.tables.BookAuthor;
import com.kenvix.bookmgr.orm.tables.BookAuthorMap;
import com.kenvix.bookmgr.orm.tables.BookBorrow;
import com.kenvix.bookmgr.orm.tables.BookBorrowExpired;
import com.kenvix.bookmgr.orm.tables.BookBorrowForAdmin;
import com.kenvix.bookmgr.orm.tables.BookForUser;
import com.kenvix.bookmgr.orm.tables.BookStatus;
import com.kenvix.bookmgr.orm.tables.BookType;
import com.kenvix.bookmgr.orm.tables.Invoice;
import com.kenvix.bookmgr.orm.tables.InvoiceForUser;
import com.kenvix.bookmgr.orm.tables.InvoicePenalty;
import com.kenvix.bookmgr.orm.tables.InvoiceStatus;
import com.kenvix.bookmgr.orm.tables.InvoiceType;
import com.kenvix.bookmgr.orm.tables.LogCardAccess;
import com.kenvix.bookmgr.orm.tables.LogCardAccessForAdmin;
import com.kenvix.bookmgr.orm.tables.LogSystem;
import com.kenvix.bookmgr.orm.tables.LogUserLogin;
import com.kenvix.bookmgr.orm.tables.LogUserLoginForAdmin;
import com.kenvix.bookmgr.orm.tables.Publisher;
import com.kenvix.bookmgr.orm.tables.Setting;
import com.kenvix.bookmgr.orm.tables.TaskQueue;
import com.kenvix.bookmgr.orm.tables.User;
import com.kenvix.bookmgr.orm.tables.UserAccessLevel;
import com.kenvix.bookmgr.orm.tables.UserExtra;
import com.kenvix.bookmgr.orm.tables.UserForAdmin;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 作者表
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * 书籍表
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * VIEW
     */
    public static final BookAuthor BOOK_AUTHOR = BookAuthor.BOOK_AUTHOR;

    /**
     * 书籍-作者关系映射表
     */
    public static final BookAuthorMap BOOK_AUTHOR_MAP = BookAuthorMap.BOOK_AUTHOR_MAP;

    /**
     * 借书表
     */
    public static final BookBorrow BOOK_BORROW = BookBorrow.BOOK_BORROW;

    /**
     * VIEW
     */
    public static final BookBorrowExpired BOOK_BORROW_EXPIRED = BookBorrowExpired.BOOK_BORROW_EXPIRED;

    /**
     * VIEW
     */
    public static final BookBorrowForAdmin BOOK_BORROW_FOR_ADMIN = BookBorrowForAdmin.BOOK_BORROW_FOR_ADMIN;

    /**
     * VIEW
     */
    public static final BookForUser BOOK_FOR_USER = BookForUser.BOOK_FOR_USER;

    /**
     * 书籍状态表
     */
    public static final BookStatus BOOK_STATUS = BookStatus.BOOK_STATUS;

    /**
     * 图书类目
     */
    public static final BookType BOOK_TYPE = BookType.BOOK_TYPE;

    /**
     * 账单，包括罚款
     */
    public static final Invoice INVOICE = Invoice.INVOICE;

    /**
     * VIEW
     */
    public static final InvoiceForUser INVOICE_FOR_USER = InvoiceForUser.INVOICE_FOR_USER;

    /**
     * 罚款型订单扩展信息
     */
    public static final InvoicePenalty INVOICE_PENALTY = InvoicePenalty.INVOICE_PENALTY;

    /**
     * 订单状态
     */
    public static final InvoiceStatus INVOICE_STATUS = InvoiceStatus.INVOICE_STATUS;

    /**
     * 订单类型
     */
    public static final InvoiceType INVOICE_TYPE = InvoiceType.INVOICE_TYPE;

    /**
     * 刷卡日志（不可修改和删除）
     */
    public static final LogCardAccess LOG_CARD_ACCESS = LogCardAccess.LOG_CARD_ACCESS;

    /**
     * VIEW
     */
    public static final LogCardAccessForAdmin LOG_CARD_ACCESS_FOR_ADMIN = LogCardAccessForAdmin.LOG_CARD_ACCESS_FOR_ADMIN;

    /**
     * 系统日志
     */
    public static final LogSystem LOG_SYSTEM = LogSystem.LOG_SYSTEM;

    /**
     * 用户登录日志（不可修改和删除）
     */
    public static final LogUserLogin LOG_USER_LOGIN = LogUserLogin.LOG_USER_LOGIN;

    /**
     * VIEW
     */
    public static final LogUserLoginForAdmin LOG_USER_LOGIN_FOR_ADMIN = LogUserLoginForAdmin.LOG_USER_LOGIN_FOR_ADMIN;

    /**
     * 出版社
     */
    public static final Publisher PUBLISHER = Publisher.PUBLISHER;

    /**
     * 设置表
     */
    public static final Setting SETTING = Setting.SETTING;

    /**
     * 任务队列（程序可读）
     */
    public static final TaskQueue TASK_QUEUE = TaskQueue.TASK_QUEUE;

    /**
     * 用户基本信息
     */
    public static final User USER = User.USER;

    /**
     * 用户访问级别定义
     */
    public static final UserAccessLevel USER_ACCESS_LEVEL = UserAccessLevel.USER_ACCESS_LEVEL;

    /**
     * 用户扩展信息
     */
    public static final UserExtra USER_EXTRA = UserExtra.USER_EXTRA;

    /**
     * VIEW
     */
    public static final UserForAdmin USER_FOR_ADMIN = UserForAdmin.USER_FOR_ADMIN;
}
