/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.pojos;


import com.kenvix.bookmgr.orm.tables.interfaces.IBook;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;


/**
 * 书籍表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Book implements IBook {

    private static final long serialVersionUID = -1512069603;

    private Long      id;
    private Long      creatorUid;
    private String    title;
    private String    description;
    private Long      publisherId;
    private Timestamp createdAt;
    private Integer   numTotal;
    private Integer   numAvailable;
    private Byte      status;

    public Book() {}

    public Book(IBook value) {
        this.id = value.getId();
        this.creatorUid = value.getCreatorUid();
        this.title = value.getTitle();
        this.description = value.getDescription();
        this.publisherId = value.getPublisherId();
        this.createdAt = value.getCreatedAt();
        this.numTotal = value.getNumTotal();
        this.numAvailable = value.getNumAvailable();
        this.status = value.getStatus();
    }

    public Book(
        Long      id,
        Long      creatorUid,
        String    title,
        String    description,
        Long      publisherId,
        Timestamp createdAt,
        Integer   numTotal,
        Integer   numAvailable,
        Byte      status
    ) {
        this.id = id;
        this.creatorUid = creatorUid;
        this.title = title;
        this.description = description;
        this.publisherId = publisherId;
        this.createdAt = createdAt;
        this.numTotal = numTotal;
        this.numAvailable = numAvailable;
        this.status = status;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public Book setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public Long getCreatorUid() {
        return this.creatorUid;
    }

    @Override
    public Book setCreatorUid(Long creatorUid) {
        this.creatorUid = creatorUid;
        return this;
    }

    @Override
    public String getTitle() {
        return this.title;
    }

    @Override
    public Book setTitle(String title) {
        this.title = title;
        return this;
    }

    @Override
    public String getDescription() {
        return this.description;
    }

    @Override
    public Book setDescription(String description) {
        this.description = description;
        return this;
    }

    @Override
    public Long getPublisherId() {
        return this.publisherId;
    }

    @Override
    public Book setPublisherId(Long publisherId) {
        this.publisherId = publisherId;
        return this;
    }

    @Override
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public Book setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public Integer getNumTotal() {
        return this.numTotal;
    }

    @Override
    public Book setNumTotal(Integer numTotal) {
        this.numTotal = numTotal;
        return this;
    }

    @Override
    public Integer getNumAvailable() {
        return this.numAvailable;
    }

    @Override
    public Book setNumAvailable(Integer numAvailable) {
        this.numAvailable = numAvailable;
        return this;
    }

    @Override
    public Byte getStatus() {
        return this.status;
    }

    @Override
    public Book setStatus(Byte status) {
        this.status = status;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Book (");

        sb.append(id);
        sb.append(", ").append(creatorUid);
        sb.append(", ").append(title);
        sb.append(", ").append(description);
        sb.append(", ").append(publisherId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(numTotal);
        sb.append(", ").append(numAvailable);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IBook from) {
        setId(from.getId());
        setCreatorUid(from.getCreatorUid());
        setTitle(from.getTitle());
        setDescription(from.getDescription());
        setPublisherId(from.getPublisherId());
        setCreatedAt(from.getCreatedAt());
        setNumTotal(from.getNumTotal());
        setNumAvailable(from.getNumAvailable());
        setStatus(from.getStatus());
    }

    @Override
    public <E extends IBook> E into(E into) {
        into.from(this);
        return into;
    }
}
