/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.pojos;


import com.kenvix.bookmgr.orm.tables.interfaces.IBookBorrowExpired;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;


/**
 * VIEW
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookBorrowExpired implements IBookBorrowExpired {

    private static final long serialVersionUID = 1L;

    private Long      bookId;
    private Long      borrowerUid;
    private Timestamp borrowedAt;
    private Timestamp expectedReturnedAt;
    private String    bookTitle;
    private String    borrowerEmail;
    private String    borrowerRealName;
    private String    borrowerSerialId;

    public BookBorrowExpired() {}

    public BookBorrowExpired(IBookBorrowExpired value) {
        this.bookId = value.getBookId();
        this.borrowerUid = value.getBorrowerUid();
        this.borrowedAt = value.getBorrowedAt();
        this.expectedReturnedAt = value.getExpectedReturnedAt();
        this.bookTitle = value.getBookTitle();
        this.borrowerEmail = value.getBorrowerEmail();
        this.borrowerRealName = value.getBorrowerRealName();
        this.borrowerSerialId = value.getBorrowerSerialId();
    }

    public BookBorrowExpired(
        Long      bookId,
        Long      borrowerUid,
        Timestamp borrowedAt,
        Timestamp expectedReturnedAt,
        String    bookTitle,
        String    borrowerEmail,
        String    borrowerRealName,
        String    borrowerSerialId
    ) {
        this.bookId = bookId;
        this.borrowerUid = borrowerUid;
        this.borrowedAt = borrowedAt;
        this.expectedReturnedAt = expectedReturnedAt;
        this.bookTitle = bookTitle;
        this.borrowerEmail = borrowerEmail;
        this.borrowerRealName = borrowerRealName;
        this.borrowerSerialId = borrowerSerialId;
    }

    /**
     * Getter for <code>book_borrow_expired.book_id</code>. 书籍ID
     */
    @Override
    public Long getBookId() {
        return this.bookId;
    }

    /**
     * Setter for <code>book_borrow_expired.book_id</code>. 书籍ID
     */
    @Override
    public BookBorrowExpired setBookId(Long bookId) {
        this.bookId = bookId;
        return this;
    }

    /**
     * Getter for <code>book_borrow_expired.borrower_uid</code>. 借书人UID
     */
    @Override
    public Long getBorrowerUid() {
        return this.borrowerUid;
    }

    /**
     * Setter for <code>book_borrow_expired.borrower_uid</code>. 借书人UID
     */
    @Override
    public BookBorrowExpired setBorrowerUid(Long borrowerUid) {
        this.borrowerUid = borrowerUid;
        return this;
    }

    /**
     * Getter for <code>book_borrow_expired.borrowed_at</code>. 借书日期
     */
    @Override
    public Timestamp getBorrowedAt() {
        return this.borrowedAt;
    }

    /**
     * Setter for <code>book_borrow_expired.borrowed_at</code>. 借书日期
     */
    @Override
    public BookBorrowExpired setBorrowedAt(Timestamp borrowedAt) {
        this.borrowedAt = borrowedAt;
        return this;
    }

    /**
     * Getter for <code>book_borrow_expired.expected_returned_at</code>. 期望的还书日期
     */
    @Override
    public Timestamp getExpectedReturnedAt() {
        return this.expectedReturnedAt;
    }

    /**
     * Setter for <code>book_borrow_expired.expected_returned_at</code>. 期望的还书日期
     */
    @Override
    public BookBorrowExpired setExpectedReturnedAt(Timestamp expectedReturnedAt) {
        this.expectedReturnedAt = expectedReturnedAt;
        return this;
    }

    /**
     * Getter for <code>book_borrow_expired.book_title</code>. 书籍标题
     */
    @Override
    public String getBookTitle() {
        return this.bookTitle;
    }

    /**
     * Setter for <code>book_borrow_expired.book_title</code>. 书籍标题
     */
    @Override
    public BookBorrowExpired setBookTitle(String bookTitle) {
        this.bookTitle = bookTitle;
        return this;
    }

    /**
     * Getter for <code>book_borrow_expired.borrower_email</code>. 电子邮箱
     */
    @Override
    public String getBorrowerEmail() {
        return this.borrowerEmail;
    }

    /**
     * Setter for <code>book_borrow_expired.borrower_email</code>. 电子邮箱
     */
    @Override
    public BookBorrowExpired setBorrowerEmail(String borrowerEmail) {
        this.borrowerEmail = borrowerEmail;
        return this;
    }

    /**
     * Getter for <code>book_borrow_expired.borrower_real_name</code>. 真实姓名
     */
    @Override
    public String getBorrowerRealName() {
        return this.borrowerRealName;
    }

    /**
     * Setter for <code>book_borrow_expired.borrower_real_name</code>. 真实姓名
     */
    @Override
    public BookBorrowExpired setBorrowerRealName(String borrowerRealName) {
        this.borrowerRealName = borrowerRealName;
        return this;
    }

    /**
     * Getter for <code>book_borrow_expired.borrower_serial_id</code>. 工号/序列号
     */
    @Override
    public String getBorrowerSerialId() {
        return this.borrowerSerialId;
    }

    /**
     * Setter for <code>book_borrow_expired.borrower_serial_id</code>. 工号/序列号
     */
    @Override
    public BookBorrowExpired setBorrowerSerialId(String borrowerSerialId) {
        this.borrowerSerialId = borrowerSerialId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BookBorrowExpired (");

        sb.append(bookId);
        sb.append(", ").append(borrowerUid);
        sb.append(", ").append(borrowedAt);
        sb.append(", ").append(expectedReturnedAt);
        sb.append(", ").append(bookTitle);
        sb.append(", ").append(borrowerEmail);
        sb.append(", ").append(borrowerRealName);
        sb.append(", ").append(borrowerSerialId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IBookBorrowExpired from) {
        setBookId(from.getBookId());
        setBorrowerUid(from.getBorrowerUid());
        setBorrowedAt(from.getBorrowedAt());
        setExpectedReturnedAt(from.getExpectedReturnedAt());
        setBookTitle(from.getBookTitle());
        setBorrowerEmail(from.getBorrowerEmail());
        setBorrowerRealName(from.getBorrowerRealName());
        setBorrowerSerialId(from.getBorrowerSerialId());
    }

    @Override
    public <E extends IBookBorrowExpired> E into(E into) {
        into.from(this);
        return into;
    }
}
