/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.pojos;


import com.kenvix.bookmgr.orm.tables.interfaces.IBookForUser;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;


/**
 * VIEW
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookForUser implements IBookForUser {

    private static final long serialVersionUID = -883929816;

    private Long      id;
    private String    title;
    private String    description;
    private Long      publisherId;
    private Timestamp createdAt;
    private Integer   numTotal;
    private Integer   numAvailable;
    private Byte      status;
    private String    publisherName;
    private String    publisherDescription;

    public BookForUser() {}

    public BookForUser(IBookForUser value) {
        this.id = value.getId();
        this.title = value.getTitle();
        this.description = value.getDescription();
        this.publisherId = value.getPublisherId();
        this.createdAt = value.getCreatedAt();
        this.numTotal = value.getNumTotal();
        this.numAvailable = value.getNumAvailable();
        this.status = value.getStatus();
        this.publisherName = value.getPublisherName();
        this.publisherDescription = value.getPublisherDescription();
    }

    public BookForUser(
        Long      id,
        String    title,
        String    description,
        Long      publisherId,
        Timestamp createdAt,
        Integer   numTotal,
        Integer   numAvailable,
        Byte      status,
        String    publisherName,
        String    publisherDescription
    ) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.publisherId = publisherId;
        this.createdAt = createdAt;
        this.numTotal = numTotal;
        this.numAvailable = numAvailable;
        this.status = status;
        this.publisherName = publisherName;
        this.publisherDescription = publisherDescription;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public BookForUser setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getTitle() {
        return this.title;
    }

    @Override
    public BookForUser setTitle(String title) {
        this.title = title;
        return this;
    }

    @Override
    public String getDescription() {
        return this.description;
    }

    @Override
    public BookForUser setDescription(String description) {
        this.description = description;
        return this;
    }

    @Override
    public Long getPublisherId() {
        return this.publisherId;
    }

    @Override
    public BookForUser setPublisherId(Long publisherId) {
        this.publisherId = publisherId;
        return this;
    }

    @Override
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public BookForUser setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public Integer getNumTotal() {
        return this.numTotal;
    }

    @Override
    public BookForUser setNumTotal(Integer numTotal) {
        this.numTotal = numTotal;
        return this;
    }

    @Override
    public Integer getNumAvailable() {
        return this.numAvailable;
    }

    @Override
    public BookForUser setNumAvailable(Integer numAvailable) {
        this.numAvailable = numAvailable;
        return this;
    }

    @Override
    public Byte getStatus() {
        return this.status;
    }

    @Override
    public BookForUser setStatus(Byte status) {
        this.status = status;
        return this;
    }

    @Override
    public String getPublisherName() {
        return this.publisherName;
    }

    @Override
    public BookForUser setPublisherName(String publisherName) {
        this.publisherName = publisherName;
        return this;
    }

    @Override
    public String getPublisherDescription() {
        return this.publisherDescription;
    }

    @Override
    public BookForUser setPublisherDescription(String publisherDescription) {
        this.publisherDescription = publisherDescription;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BookForUser (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(description);
        sb.append(", ").append(publisherId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(numTotal);
        sb.append(", ").append(numAvailable);
        sb.append(", ").append(status);
        sb.append(", ").append(publisherName);
        sb.append(", ").append(publisherDescription);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IBookForUser from) {
        setId(from.getId());
        setTitle(from.getTitle());
        setDescription(from.getDescription());
        setPublisherId(from.getPublisherId());
        setCreatedAt(from.getCreatedAt());
        setNumTotal(from.getNumTotal());
        setNumAvailable(from.getNumAvailable());
        setStatus(from.getStatus());
        setPublisherName(from.getPublisherName());
        setPublisherDescription(from.getPublisherDescription());
    }

    @Override
    public <E extends IBookForUser> E into(E into) {
        into.from(this);
        return into;
    }
}
