/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.pojos;


import com.kenvix.bookmgr.orm.tables.interfaces.IBookAuthor;

import javax.annotation.processing.Generated;


/**
 * VIEW
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookAuthor implements IBookAuthor {

    private static final long serialVersionUID = 998415670;

    private Long   bookId;
    private Long   authorId;
    private String authorName;
    private String authorFullname;
    private String authorCountry;
    private String authorDescription;

    public BookAuthor() {}

    public BookAuthor(IBookAuthor value) {
        this.bookId = value.getBookId();
        this.authorId = value.getAuthorId();
        this.authorName = value.getAuthorName();
        this.authorFullname = value.getAuthorFullname();
        this.authorCountry = value.getAuthorCountry();
        this.authorDescription = value.getAuthorDescription();
    }

    public BookAuthor(
        Long   bookId,
        Long   authorId,
        String authorName,
        String authorFullname,
        String authorCountry,
        String authorDescription
    ) {
        this.bookId = bookId;
        this.authorId = authorId;
        this.authorName = authorName;
        this.authorFullname = authorFullname;
        this.authorCountry = authorCountry;
        this.authorDescription = authorDescription;
    }

    @Override
    public Long getBookId() {
        return this.bookId;
    }

    @Override
    public BookAuthor setBookId(Long bookId) {
        this.bookId = bookId;
        return this;
    }

    @Override
    public Long getAuthorId() {
        return this.authorId;
    }

    @Override
    public BookAuthor setAuthorId(Long authorId) {
        this.authorId = authorId;
        return this;
    }

    @Override
    public String getAuthorName() {
        return this.authorName;
    }

    @Override
    public BookAuthor setAuthorName(String authorName) {
        this.authorName = authorName;
        return this;
    }

    @Override
    public String getAuthorFullname() {
        return this.authorFullname;
    }

    @Override
    public BookAuthor setAuthorFullname(String authorFullname) {
        this.authorFullname = authorFullname;
        return this;
    }

    @Override
    public String getAuthorCountry() {
        return this.authorCountry;
    }

    @Override
    public BookAuthor setAuthorCountry(String authorCountry) {
        this.authorCountry = authorCountry;
        return this;
    }

    @Override
    public String getAuthorDescription() {
        return this.authorDescription;
    }

    @Override
    public BookAuthor setAuthorDescription(String authorDescription) {
        this.authorDescription = authorDescription;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BookAuthor (");

        sb.append(bookId);
        sb.append(", ").append(authorId);
        sb.append(", ").append(authorName);
        sb.append(", ").append(authorFullname);
        sb.append(", ").append(authorCountry);
        sb.append(", ").append(authorDescription);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IBookAuthor from) {
        setBookId(from.getBookId());
        setAuthorId(from.getAuthorId());
        setAuthorName(from.getAuthorName());
        setAuthorFullname(from.getAuthorFullname());
        setAuthorCountry(from.getAuthorCountry());
        setAuthorDescription(from.getAuthorDescription());
    }

    @Override
    public <E extends IBookAuthor> E into(E into) {
        into.from(this);
        return into;
    }
}
