/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.pojos;


import com.kenvix.bookmgr.orm.tables.interfaces.IBookAuthorMap;

import javax.annotation.processing.Generated;


/**
 * 书籍-作者关系映射表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookAuthorMap implements IBookAuthorMap {

    private static final long serialVersionUID = 1985042283;

    private Long bookId;
    private Long authorId;

    public BookAuthorMap() {}

    public BookAuthorMap(IBookAuthorMap value) {
        this.bookId = value.getBookId();
        this.authorId = value.getAuthorId();
    }

    public BookAuthorMap(
        Long bookId,
        Long authorId
    ) {
        this.bookId = bookId;
        this.authorId = authorId;
    }

    @Override
    public Long getBookId() {
        return this.bookId;
    }

    @Override
    public BookAuthorMap setBookId(Long bookId) {
        this.bookId = bookId;
        return this;
    }

    @Override
    public Long getAuthorId() {
        return this.authorId;
    }

    @Override
    public BookAuthorMap setAuthorId(Long authorId) {
        this.authorId = authorId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BookAuthorMap (");

        sb.append(bookId);
        sb.append(", ").append(authorId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IBookAuthorMap from) {
        setBookId(from.getBookId());
        setAuthorId(from.getAuthorId());
    }

    @Override
    public <E extends IBookAuthorMap> E into(E into) {
        into.from(this);
        return into;
    }
}
