/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.pojos;


import com.kenvix.bookmgr.orm.tables.interfaces.IBookForUser;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;


/**
 * VIEW
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookForUser implements IBookForUser {

    private static final long serialVersionUID = 1144234194;

    private Long      id;
    private String    title;
    private String    description;
    private Long      publisherId;
    private Timestamp createdAt;
    private Integer   numTotal;
    private Integer   numAvailable;
    private Byte      status;
    private String    publisherName;
    private Long      authorId;
    private String    authorName;
    private String    authorFullname;
    private String    authorCountry;
    private Long      creatorUid;
    private Integer   typeId;
    private String    typeName;
    private String    statusDescription;
    private String    isbn;

    public BookForUser() {}

    public BookForUser(IBookForUser value) {
        this.id = value.getId();
        this.title = value.getTitle();
        this.description = value.getDescription();
        this.publisherId = value.getPublisherId();
        this.createdAt = value.getCreatedAt();
        this.numTotal = value.getNumTotal();
        this.numAvailable = value.getNumAvailable();
        this.status = value.getStatus();
        this.publisherName = value.getPublisherName();
        this.authorId = value.getAuthorId();
        this.authorName = value.getAuthorName();
        this.authorFullname = value.getAuthorFullname();
        this.authorCountry = value.getAuthorCountry();
        this.creatorUid = value.getCreatorUid();
        this.typeId = value.getTypeId();
        this.typeName = value.getTypeName();
        this.statusDescription = value.getStatusDescription();
        this.isbn = value.getIsbn();
    }

    public BookForUser(
        Long      id,
        String    title,
        String    description,
        Long      publisherId,
        Timestamp createdAt,
        Integer   numTotal,
        Integer   numAvailable,
        Byte      status,
        String    publisherName,
        Long      authorId,
        String    authorName,
        String    authorFullname,
        String    authorCountry,
        Long      creatorUid,
        Integer   typeId,
        String    typeName,
        String    statusDescription,
        String    isbn
    ) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.publisherId = publisherId;
        this.createdAt = createdAt;
        this.numTotal = numTotal;
        this.numAvailable = numAvailable;
        this.status = status;
        this.publisherName = publisherName;
        this.authorId = authorId;
        this.authorName = authorName;
        this.authorFullname = authorFullname;
        this.authorCountry = authorCountry;
        this.creatorUid = creatorUid;
        this.typeId = typeId;
        this.typeName = typeName;
        this.statusDescription = statusDescription;
        this.isbn = isbn;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public BookForUser setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getTitle() {
        return this.title;
    }

    @Override
    public BookForUser setTitle(String title) {
        this.title = title;
        return this;
    }

    @Override
    public String getDescription() {
        return this.description;
    }

    @Override
    public BookForUser setDescription(String description) {
        this.description = description;
        return this;
    }

    @Override
    public Long getPublisherId() {
        return this.publisherId;
    }

    @Override
    public BookForUser setPublisherId(Long publisherId) {
        this.publisherId = publisherId;
        return this;
    }

    @Override
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public BookForUser setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public Integer getNumTotal() {
        return this.numTotal;
    }

    @Override
    public BookForUser setNumTotal(Integer numTotal) {
        this.numTotal = numTotal;
        return this;
    }

    @Override
    public Integer getNumAvailable() {
        return this.numAvailable;
    }

    @Override
    public BookForUser setNumAvailable(Integer numAvailable) {
        this.numAvailable = numAvailable;
        return this;
    }

    @Override
    public Byte getStatus() {
        return this.status;
    }

    @Override
    public BookForUser setStatus(Byte status) {
        this.status = status;
        return this;
    }

    @Override
    public String getPublisherName() {
        return this.publisherName;
    }

    @Override
    public BookForUser setPublisherName(String publisherName) {
        this.publisherName = publisherName;
        return this;
    }

    @Override
    public Long getAuthorId() {
        return this.authorId;
    }

    @Override
    public BookForUser setAuthorId(Long authorId) {
        this.authorId = authorId;
        return this;
    }

    @Override
    public String getAuthorName() {
        return this.authorName;
    }

    @Override
    public BookForUser setAuthorName(String authorName) {
        this.authorName = authorName;
        return this;
    }

    @Override
    public String getAuthorFullname() {
        return this.authorFullname;
    }

    @Override
    public BookForUser setAuthorFullname(String authorFullname) {
        this.authorFullname = authorFullname;
        return this;
    }

    @Override
    public String getAuthorCountry() {
        return this.authorCountry;
    }

    @Override
    public BookForUser setAuthorCountry(String authorCountry) {
        this.authorCountry = authorCountry;
        return this;
    }

    @Override
    public Long getCreatorUid() {
        return this.creatorUid;
    }

    @Override
    public BookForUser setCreatorUid(Long creatorUid) {
        this.creatorUid = creatorUid;
        return this;
    }

    @Override
    public Integer getTypeId() {
        return this.typeId;
    }

    @Override
    public BookForUser setTypeId(Integer typeId) {
        this.typeId = typeId;
        return this;
    }

    @Override
    public String getTypeName() {
        return this.typeName;
    }

    @Override
    public BookForUser setTypeName(String typeName) {
        this.typeName = typeName;
        return this;
    }

    @Override
    public String getStatusDescription() {
        return this.statusDescription;
    }

    @Override
    public BookForUser setStatusDescription(String statusDescription) {
        this.statusDescription = statusDescription;
        return this;
    }

    @Override
    public String getIsbn() {
        return this.isbn;
    }

    @Override
    public BookForUser setIsbn(String isbn) {
        this.isbn = isbn;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BookForUser (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(description);
        sb.append(", ").append(publisherId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(numTotal);
        sb.append(", ").append(numAvailable);
        sb.append(", ").append(status);
        sb.append(", ").append(publisherName);
        sb.append(", ").append(authorId);
        sb.append(", ").append(authorName);
        sb.append(", ").append(authorFullname);
        sb.append(", ").append(authorCountry);
        sb.append(", ").append(creatorUid);
        sb.append(", ").append(typeId);
        sb.append(", ").append(typeName);
        sb.append(", ").append(statusDescription);
        sb.append(", ").append(isbn);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IBookForUser from) {
        setId(from.getId());
        setTitle(from.getTitle());
        setDescription(from.getDescription());
        setPublisherId(from.getPublisherId());
        setCreatedAt(from.getCreatedAt());
        setNumTotal(from.getNumTotal());
        setNumAvailable(from.getNumAvailable());
        setStatus(from.getStatus());
        setPublisherName(from.getPublisherName());
        setAuthorId(from.getAuthorId());
        setAuthorName(from.getAuthorName());
        setAuthorFullname(from.getAuthorFullname());
        setAuthorCountry(from.getAuthorCountry());
        setCreatorUid(from.getCreatorUid());
        setTypeId(from.getTypeId());
        setTypeName(from.getTypeName());
        setStatusDescription(from.getStatusDescription());
        setIsbn(from.getIsbn());
    }

    @Override
    public <E extends IBookForUser> E into(E into) {
        into.from(this);
        return into;
    }
}
