/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.pojos;


import com.kenvix.bookmgr.orm.tables.interfaces.IBookForUser;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;


/**
 * VIEW
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookForUser implements IBookForUser {

    private static final long serialVersionUID = 1L;

    private Long      id;
    private String    title;
    private String    description;
    private Long      publisherId;
    private Timestamp createdAt;
    private Integer   numTotal;
    private Integer   numAvailable;
    private Byte      status;
    private String    publisherName;
    private Long      authorId;
    private String    authorName;
    private String    authorFullname;
    private String    authorCountry;
    private Long      creatorUid;
    private Integer   typeId;
    private String    typeName;
    private String    statusDescription;
    private String    isbn;

    public BookForUser() {}

    public BookForUser(IBookForUser value) {
        this.id = value.getId();
        this.title = value.getTitle();
        this.description = value.getDescription();
        this.publisherId = value.getPublisherId();
        this.createdAt = value.getCreatedAt();
        this.numTotal = value.getNumTotal();
        this.numAvailable = value.getNumAvailable();
        this.status = value.getStatus();
        this.publisherName = value.getPublisherName();
        this.authorId = value.getAuthorId();
        this.authorName = value.getAuthorName();
        this.authorFullname = value.getAuthorFullname();
        this.authorCountry = value.getAuthorCountry();
        this.creatorUid = value.getCreatorUid();
        this.typeId = value.getTypeId();
        this.typeName = value.getTypeName();
        this.statusDescription = value.getStatusDescription();
        this.isbn = value.getIsbn();
    }

    public BookForUser(
        Long      id,
        String    title,
        String    description,
        Long      publisherId,
        Timestamp createdAt,
        Integer   numTotal,
        Integer   numAvailable,
        Byte      status,
        String    publisherName,
        Long      authorId,
        String    authorName,
        String    authorFullname,
        String    authorCountry,
        Long      creatorUid,
        Integer   typeId,
        String    typeName,
        String    statusDescription,
        String    isbn
    ) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.publisherId = publisherId;
        this.createdAt = createdAt;
        this.numTotal = numTotal;
        this.numAvailable = numAvailable;
        this.status = status;
        this.publisherName = publisherName;
        this.authorId = authorId;
        this.authorName = authorName;
        this.authorFullname = authorFullname;
        this.authorCountry = authorCountry;
        this.creatorUid = creatorUid;
        this.typeId = typeId;
        this.typeName = typeName;
        this.statusDescription = statusDescription;
        this.isbn = isbn;
    }

    /**
     * Getter for <code>book_for_user.id</code>. 书本ID
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>book_for_user.id</code>. 书本ID
     */
    @Override
    public BookForUser setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>book_for_user.title</code>. 书籍标题
     */
    @Override
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>book_for_user.title</code>. 书籍标题
     */
    @Override
    public BookForUser setTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Getter for <code>book_for_user.description</code>. 书籍概述
     */
    @Override
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>book_for_user.description</code>. 书籍概述
     */
    @Override
    public BookForUser setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Getter for <code>book_for_user.publisher_id</code>. 出版社ID
     */
    @Override
    public Long getPublisherId() {
        return this.publisherId;
    }

    /**
     * Setter for <code>book_for_user.publisher_id</code>. 出版社ID
     */
    @Override
    public BookForUser setPublisherId(Long publisherId) {
        this.publisherId = publisherId;
        return this;
    }

    /**
     * Getter for <code>book_for_user.created_at</code>. 条目创建时间
     */
    @Override
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>book_for_user.created_at</code>. 条目创建时间
     */
    @Override
    public BookForUser setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>book_for_user.num_total</code>. 书籍总数
     */
    @Override
    public Integer getNumTotal() {
        return this.numTotal;
    }

    /**
     * Setter for <code>book_for_user.num_total</code>. 书籍总数
     */
    @Override
    public BookForUser setNumTotal(Integer numTotal) {
        this.numTotal = numTotal;
        return this;
    }

    /**
     * Getter for <code>book_for_user.num_available</code>. 可用书籍数
     */
    @Override
    public Integer getNumAvailable() {
        return this.numAvailable;
    }

    /**
     * Setter for <code>book_for_user.num_available</code>. 可用书籍数
     */
    @Override
    public BookForUser setNumAvailable(Integer numAvailable) {
        this.numAvailable = numAvailable;
        return this;
    }

    /**
     * Getter for <code>book_for_user.status</code>. 书籍状态
     */
    @Override
    public Byte getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>book_for_user.status</code>. 书籍状态
     */
    @Override
    public BookForUser setStatus(Byte status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>book_for_user.publisher_name</code>. 出版社名称
     */
    @Override
    public String getPublisherName() {
        return this.publisherName;
    }

    /**
     * Setter for <code>book_for_user.publisher_name</code>. 出版社名称
     */
    @Override
    public BookForUser setPublisherName(String publisherName) {
        this.publisherName = publisherName;
        return this;
    }

    /**
     * Getter for <code>book_for_user.author_id</code>. 作者ID
     */
    @Override
    public Long getAuthorId() {
        return this.authorId;
    }

    /**
     * Setter for <code>book_for_user.author_id</code>. 作者ID
     */
    @Override
    public BookForUser setAuthorId(Long authorId) {
        this.authorId = authorId;
        return this;
    }

    /**
     * Getter for <code>book_for_user.author_name</code>.
     */
    @Override
    public String getAuthorName() {
        return this.authorName;
    }

    /**
     * Setter for <code>book_for_user.author_name</code>.
     */
    @Override
    public BookForUser setAuthorName(String authorName) {
        this.authorName = authorName;
        return this;
    }

    /**
     * Getter for <code>book_for_user.author_fullname</code>.
     */
    @Override
    public String getAuthorFullname() {
        return this.authorFullname;
    }

    /**
     * Setter for <code>book_for_user.author_fullname</code>.
     */
    @Override
    public BookForUser setAuthorFullname(String authorFullname) {
        this.authorFullname = authorFullname;
        return this;
    }

    /**
     * Getter for <code>book_for_user.author_country</code>.
     */
    @Override
    public String getAuthorCountry() {
        return this.authorCountry;
    }

    /**
     * Setter for <code>book_for_user.author_country</code>.
     */
    @Override
    public BookForUser setAuthorCountry(String authorCountry) {
        this.authorCountry = authorCountry;
        return this;
    }

    /**
     * Getter for <code>book_for_user.creator_uid</code>. 条目创建者UID
     */
    @Override
    public Long getCreatorUid() {
        return this.creatorUid;
    }

    /**
     * Setter for <code>book_for_user.creator_uid</code>. 条目创建者UID
     */
    @Override
    public BookForUser setCreatorUid(Long creatorUid) {
        this.creatorUid = creatorUid;
        return this;
    }

    /**
     * Getter for <code>book_for_user.type_id</code>. 图书类型ID
     */
    @Override
    public Integer getTypeId() {
        return this.typeId;
    }

    /**
     * Setter for <code>book_for_user.type_id</code>. 图书类型ID
     */
    @Override
    public BookForUser setTypeId(Integer typeId) {
        this.typeId = typeId;
        return this;
    }

    /**
     * Getter for <code>book_for_user.type_name</code>. 类目名称
     */
    @Override
    public String getTypeName() {
        return this.typeName;
    }

    /**
     * Setter for <code>book_for_user.type_name</code>. 类目名称
     */
    @Override
    public BookForUser setTypeName(String typeName) {
        this.typeName = typeName;
        return this;
    }

    /**
     * Getter for <code>book_for_user.status_description</code>.
     */
    @Override
    public String getStatusDescription() {
        return this.statusDescription;
    }

    /**
     * Setter for <code>book_for_user.status_description</code>.
     */
    @Override
    public BookForUser setStatusDescription(String statusDescription) {
        this.statusDescription = statusDescription;
        return this;
    }

    /**
     * Getter for <code>book_for_user.isbn</code>. 国际标准书号 (International Standard Book Number)
     */
    @Override
    public String getIsbn() {
        return this.isbn;
    }

    /**
     * Setter for <code>book_for_user.isbn</code>. 国际标准书号 (International Standard Book Number)
     */
    @Override
    public BookForUser setIsbn(String isbn) {
        this.isbn = isbn;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BookForUser (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(description);
        sb.append(", ").append(publisherId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(numTotal);
        sb.append(", ").append(numAvailable);
        sb.append(", ").append(status);
        sb.append(", ").append(publisherName);
        sb.append(", ").append(authorId);
        sb.append(", ").append(authorName);
        sb.append(", ").append(authorFullname);
        sb.append(", ").append(authorCountry);
        sb.append(", ").append(creatorUid);
        sb.append(", ").append(typeId);
        sb.append(", ").append(typeName);
        sb.append(", ").append(statusDescription);
        sb.append(", ").append(isbn);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IBookForUser from) {
        setId(from.getId());
        setTitle(from.getTitle());
        setDescription(from.getDescription());
        setPublisherId(from.getPublisherId());
        setCreatedAt(from.getCreatedAt());
        setNumTotal(from.getNumTotal());
        setNumAvailable(from.getNumAvailable());
        setStatus(from.getStatus());
        setPublisherName(from.getPublisherName());
        setAuthorId(from.getAuthorId());
        setAuthorName(from.getAuthorName());
        setAuthorFullname(from.getAuthorFullname());
        setAuthorCountry(from.getAuthorCountry());
        setCreatorUid(from.getCreatorUid());
        setTypeId(from.getTypeId());
        setTypeName(from.getTypeName());
        setStatusDescription(from.getStatusDescription());
        setIsbn(from.getIsbn());
    }

    @Override
    public <E extends IBookForUser> E into(E into) {
        into.from(this);
        return into;
    }
}
