/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.pojos;


import com.kenvix.bookmgr.orm.tables.interfaces.IBookType;

import javax.annotation.processing.Generated;


/**
 * 图书类目
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookType implements IBookType {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  name;
    private Integer parentId;

    public BookType() {}

    public BookType(IBookType value) {
        this.id = value.getId();
        this.name = value.getName();
        this.parentId = value.getParentId();
    }

    public BookType(
        Integer id,
        String  name,
        Integer parentId
    ) {
        this.id = id;
        this.name = name;
        this.parentId = parentId;
    }

    /**
     * Getter for <code>book_type.id</code>. 图书类目ID
     */
    @Override
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>book_type.id</code>. 图书类目ID
     */
    @Override
    public BookType setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>book_type.name</code>. 类目名称
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>book_type.name</code>. 类目名称
     */
    @Override
    public BookType setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>book_type.parent_id</code>. 父级图书类目ID
     */
    @Override
    public Integer getParentId() {
        return this.parentId;
    }

    /**
     * Setter for <code>book_type.parent_id</code>. 父级图书类目ID
     */
    @Override
    public BookType setParentId(Integer parentId) {
        this.parentId = parentId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BookType (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(parentId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IBookType from) {
        setId(from.getId());
        setName(from.getName());
        setParentId(from.getParentId());
    }

    @Override
    public <E extends IBookType> E into(E into) {
        into.from(this);
        return into;
    }
}
