/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.pojos;


import com.kenvix.bookmgr.orm.tables.interfaces.ILogCardAccessForAdmin;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;


/**
 * VIEW
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LogCardAccessForAdmin implements ILogCardAccessForAdmin {

    private static final long serialVersionUID = -1136391082;

    private Long      serialId;
    private Long      cardSerialId;
    private Long      uid;
    private Timestamp time;
    private Integer   machineId;
    private String    email;
    private String    realName;

    public LogCardAccessForAdmin() {}

    public LogCardAccessForAdmin(ILogCardAccessForAdmin value) {
        this.serialId = value.getSerialId();
        this.cardSerialId = value.getCardSerialId();
        this.uid = value.getUid();
        this.time = value.getTime();
        this.machineId = value.getMachineId();
        this.email = value.getEmail();
        this.realName = value.getRealName();
    }

    public LogCardAccessForAdmin(
        Long      serialId,
        Long      cardSerialId,
        Long      uid,
        Timestamp time,
        Integer   machineId,
        String    email,
        String    realName
    ) {
        this.serialId = serialId;
        this.cardSerialId = cardSerialId;
        this.uid = uid;
        this.time = time;
        this.machineId = machineId;
        this.email = email;
        this.realName = realName;
    }

    @Override
    public Long getSerialId() {
        return this.serialId;
    }

    @Override
    public LogCardAccessForAdmin setSerialId(Long serialId) {
        this.serialId = serialId;
        return this;
    }

    @Override
    public Long getCardSerialId() {
        return this.cardSerialId;
    }

    @Override
    public LogCardAccessForAdmin setCardSerialId(Long cardSerialId) {
        this.cardSerialId = cardSerialId;
        return this;
    }

    @Override
    public Long getUid() {
        return this.uid;
    }

    @Override
    public LogCardAccessForAdmin setUid(Long uid) {
        this.uid = uid;
        return this;
    }

    @Override
    public Timestamp getTime() {
        return this.time;
    }

    @Override
    public LogCardAccessForAdmin setTime(Timestamp time) {
        this.time = time;
        return this;
    }

    @Override
    public Integer getMachineId() {
        return this.machineId;
    }

    @Override
    public LogCardAccessForAdmin setMachineId(Integer machineId) {
        this.machineId = machineId;
        return this;
    }

    @Override
    public String getEmail() {
        return this.email;
    }

    @Override
    public LogCardAccessForAdmin setEmail(String email) {
        this.email = email;
        return this;
    }

    @Override
    public String getRealName() {
        return this.realName;
    }

    @Override
    public LogCardAccessForAdmin setRealName(String realName) {
        this.realName = realName;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LogCardAccessForAdmin (");

        sb.append(serialId);
        sb.append(", ").append(cardSerialId);
        sb.append(", ").append(uid);
        sb.append(", ").append(time);
        sb.append(", ").append(machineId);
        sb.append(", ").append(email);
        sb.append(", ").append(realName);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ILogCardAccessForAdmin from) {
        setSerialId(from.getSerialId());
        setCardSerialId(from.getCardSerialId());
        setUid(from.getUid());
        setTime(from.getTime());
        setMachineId(from.getMachineId());
        setEmail(from.getEmail());
        setRealName(from.getRealName());
    }

    @Override
    public <E extends ILogCardAccessForAdmin> E into(E into) {
        into.from(this);
        return into;
    }
}
