/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.pojos;


import com.kenvix.bookmgr.orm.tables.interfaces.ILogCardAccess;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;


/**
 * 刷卡日志（不可修改和删除）
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LogCardAccess implements ILogCardAccess {

    private static final long serialVersionUID = 1044509163;

    private Long      id;
    private Long      serialId;
    private Boolean   isSuccess;
    private Timestamp time;
    private Integer   machineId;

    public LogCardAccess() {}

    public LogCardAccess(ILogCardAccess value) {
        this.id = value.getId();
        this.serialId = value.getSerialId();
        this.isSuccess = value.getIsSuccess();
        this.time = value.getTime();
        this.machineId = value.getMachineId();
    }

    public LogCardAccess(
        Long      id,
        Long      serialId,
        Boolean   isSuccess,
        Timestamp time,
        Integer   machineId
    ) {
        this.id = id;
        this.serialId = serialId;
        this.isSuccess = isSuccess;
        this.time = time;
        this.machineId = machineId;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public LogCardAccess setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public Long getSerialId() {
        return this.serialId;
    }

    @Override
    public LogCardAccess setSerialId(Long serialId) {
        this.serialId = serialId;
        return this;
    }

    @Override
    public Boolean getIsSuccess() {
        return this.isSuccess;
    }

    @Override
    public LogCardAccess setIsSuccess(Boolean isSuccess) {
        this.isSuccess = isSuccess;
        return this;
    }

    @Override
    public Timestamp getTime() {
        return this.time;
    }

    @Override
    public LogCardAccess setTime(Timestamp time) {
        this.time = time;
        return this;
    }

    @Override
    public Integer getMachineId() {
        return this.machineId;
    }

    @Override
    public LogCardAccess setMachineId(Integer machineId) {
        this.machineId = machineId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LogCardAccess (");

        sb.append(id);
        sb.append(", ").append(serialId);
        sb.append(", ").append(isSuccess);
        sb.append(", ").append(time);
        sb.append(", ").append(machineId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ILogCardAccess from) {
        setId(from.getId());
        setSerialId(from.getSerialId());
        setIsSuccess(from.getIsSuccess());
        setTime(from.getTime());
        setMachineId(from.getMachineId());
    }

    @Override
    public <E extends ILogCardAccess> E into(E into) {
        into.from(this);
        return into;
    }
}
