/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.pojos;


import com.kenvix.bookmgr.orm.tables.interfaces.ILogUserLogin;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;


/**
 * 用户登录日志（不可修改和删除）
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LogUserLogin implements ILogUserLogin {

    private static final long serialVersionUID = 846384135;

    private Long      id;
    private Long      uid;
    private Timestamp time;
    private String    ip;
    private String    useragent;

    public LogUserLogin() {}

    public LogUserLogin(ILogUserLogin value) {
        this.id = value.getId();
        this.uid = value.getUid();
        this.time = value.getTime();
        this.ip = value.getIp();
        this.useragent = value.getUseragent();
    }

    public LogUserLogin(
        Long      id,
        Long      uid,
        Timestamp time,
        String    ip,
        String    useragent
    ) {
        this.id = id;
        this.uid = uid;
        this.time = time;
        this.ip = ip;
        this.useragent = useragent;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public LogUserLogin setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public Long getUid() {
        return this.uid;
    }

    @Override
    public LogUserLogin setUid(Long uid) {
        this.uid = uid;
        return this;
    }

    @Override
    public Timestamp getTime() {
        return this.time;
    }

    @Override
    public LogUserLogin setTime(Timestamp time) {
        this.time = time;
        return this;
    }

    @Override
    public String getIp() {
        return this.ip;
    }

    @Override
    public LogUserLogin setIp(String ip) {
        this.ip = ip;
        return this;
    }

    @Override
    public String getUseragent() {
        return this.useragent;
    }

    @Override
    public LogUserLogin setUseragent(String useragent) {
        this.useragent = useragent;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LogUserLogin (");

        sb.append(id);
        sb.append(", ").append(uid);
        sb.append(", ").append(time);
        sb.append(", ").append(ip);
        sb.append(", ").append(useragent);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ILogUserLogin from) {
        setId(from.getId());
        setUid(from.getUid());
        setTime(from.getTime());
        setIp(from.getIp());
        setUseragent(from.getUseragent());
    }

    @Override
    public <E extends ILogUserLogin> E into(E into) {
        into.from(this);
        return into;
    }
}
