/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.pojos;


import com.kenvix.bookmgr.orm.tables.interfaces.IPublisher;

import javax.annotation.processing.Generated;


/**
 * 出版社
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Publisher implements IPublisher {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private String name;
    private String description;

    public Publisher() {}

    public Publisher(IPublisher value) {
        this.id = value.getId();
        this.name = value.getName();
        this.description = value.getDescription();
    }

    public Publisher(
        Long   id,
        String name,
        String description
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
    }

    /**
     * Getter for <code>publisher.id</code>. 出版社ID
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>publisher.id</code>. 出版社ID
     */
    @Override
    public Publisher setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>publisher.name</code>. 出版社名称
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>publisher.name</code>. 出版社名称
     */
    @Override
    public Publisher setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>publisher.description</code>. 出版社简介
     */
    @Override
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>publisher.description</code>. 出版社简介
     */
    @Override
    public Publisher setDescription(String description) {
        this.description = description;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Publisher (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IPublisher from) {
        setId(from.getId());
        setName(from.getName());
        setDescription(from.getDescription());
    }

    @Override
    public <E extends IPublisher> E into(E into) {
        into.from(this);
        return into;
    }
}
