/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.pojos;


import com.kenvix.bookmgr.orm.tables.interfaces.ISetting;

import javax.annotation.processing.Generated;


/**
 * 设置表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Setting implements ISetting {

    private static final long serialVersionUID = -2040557066;

    private String key;
    private String value;
    private String description;
    private String type;

    public Setting() {}

    public Setting(ISetting value) {
        this.key = value.getKey();
        this.value = value.getValue();
        this.description = value.getDescription();
        this.type = value.getType();
    }

    public Setting(
        String key,
        String value,
        String description,
        String type
    ) {
        this.key = key;
        this.value = value;
        this.description = description;
        this.type = type;
    }

    @Override
    public String getKey() {
        return this.key;
    }

    @Override
    public Setting setKey(String key) {
        this.key = key;
        return this;
    }

    @Override
    public String getValue() {
        return this.value;
    }

    @Override
    public Setting setValue(String value) {
        this.value = value;
        return this;
    }

    @Override
    public String getDescription() {
        return this.description;
    }

    @Override
    public Setting setDescription(String description) {
        this.description = description;
        return this;
    }

    @Override
    public String getType() {
        return this.type;
    }

    @Override
    public Setting setType(String type) {
        this.type = type;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Setting (");

        sb.append(key);
        sb.append(", ").append(value);
        sb.append(", ").append(description);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ISetting from) {
        setKey(from.getKey());
        setValue(from.getValue());
        setDescription(from.getDescription());
        setType(from.getType());
    }

    @Override
    public <E extends ISetting> E into(E into) {
        into.from(this);
        return into;
    }
}
