/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.pojos;


import com.kenvix.bookmgr.orm.tables.interfaces.IUserForAdmin;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;


/**
 * VIEW
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserForAdmin implements IUserForAdmin {

    private static final long serialVersionUID = 1L;

    private Long      uid;
    private String    serialId;
    private String    email;
    private String    realName;
    private String    password;
    private Byte      accessLevel;
    private String    accessLevelDescription;
    private Timestamp createdAt;
    private Long      phone;
    private Integer   money;
    private Long      cardSerialId;
    private Short     startYear;
    private String    department;
    private String    comment;
    private String    ipCreation;
    private String    ipLogin;

    public UserForAdmin() {}

    public UserForAdmin(IUserForAdmin value) {
        this.uid = value.getUid();
        this.serialId = value.getSerialId();
        this.email = value.getEmail();
        this.realName = value.getRealName();
        this.password = value.getPassword();
        this.accessLevel = value.getAccessLevel();
        this.accessLevelDescription = value.getAccessLevelDescription();
        this.createdAt = value.getCreatedAt();
        this.phone = value.getPhone();
        this.money = value.getMoney();
        this.cardSerialId = value.getCardSerialId();
        this.startYear = value.getStartYear();
        this.department = value.getDepartment();
        this.comment = value.getComment();
        this.ipCreation = value.getIpCreation();
        this.ipLogin = value.getIpLogin();
    }

    public UserForAdmin(
        Long      uid,
        String    serialId,
        String    email,
        String    realName,
        String    password,
        Byte      accessLevel,
        String    accessLevelDescription,
        Timestamp createdAt,
        Long      phone,
        Integer   money,
        Long      cardSerialId,
        Short     startYear,
        String    department,
        String    comment,
        String    ipCreation,
        String    ipLogin
    ) {
        this.uid = uid;
        this.serialId = serialId;
        this.email = email;
        this.realName = realName;
        this.password = password;
        this.accessLevel = accessLevel;
        this.accessLevelDescription = accessLevelDescription;
        this.createdAt = createdAt;
        this.phone = phone;
        this.money = money;
        this.cardSerialId = cardSerialId;
        this.startYear = startYear;
        this.department = department;
        this.comment = comment;
        this.ipCreation = ipCreation;
        this.ipLogin = ipLogin;
    }

    /**
     * Getter for <code>user_for_admin.uid</code>. 用户UID
     */
    @Override
    public Long getUid() {
        return this.uid;
    }

    /**
     * Setter for <code>user_for_admin.uid</code>. 用户UID
     */
    @Override
    public UserForAdmin setUid(Long uid) {
        this.uid = uid;
        return this;
    }

    /**
     * Getter for <code>user_for_admin.serial_id</code>. 工号/序列号
     */
    @Override
    public String getSerialId() {
        return this.serialId;
    }

    /**
     * Setter for <code>user_for_admin.serial_id</code>. 工号/序列号
     */
    @Override
    public UserForAdmin setSerialId(String serialId) {
        this.serialId = serialId;
        return this;
    }

    /**
     * Getter for <code>user_for_admin.email</code>. 电子邮箱
     */
    @Override
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>user_for_admin.email</code>. 电子邮箱
     */
    @Override
    public UserForAdmin setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>user_for_admin.real_name</code>. 真实姓名
     */
    @Override
    public String getRealName() {
        return this.realName;
    }

    /**
     * Setter for <code>user_for_admin.real_name</code>. 真实姓名
     */
    @Override
    public UserForAdmin setRealName(String realName) {
        this.realName = realName;
        return this;
    }

    /**
     * Getter for <code>user_for_admin.password</code>. Bcrypt密码哈希值
     */
    @Override
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>user_for_admin.password</code>. Bcrypt密码哈希值
     */
    @Override
    public UserForAdmin setPassword(String password) {
        this.password = password;
        return this;
    }

    /**
     * Getter for <code>user_for_admin.access_level</code>. 访问级别
     */
    @Override
    public Byte getAccessLevel() {
        return this.accessLevel;
    }

    /**
     * Setter for <code>user_for_admin.access_level</code>. 访问级别
     */
    @Override
    public UserForAdmin setAccessLevel(Byte accessLevel) {
        this.accessLevel = accessLevel;
        return this;
    }

    /**
     * Getter for <code>user_for_admin.access_level_description</code>.
     */
    @Override
    public String getAccessLevelDescription() {
        return this.accessLevelDescription;
    }

    /**
     * Setter for <code>user_for_admin.access_level_description</code>.
     */
    @Override
    public UserForAdmin setAccessLevelDescription(String accessLevelDescription) {
        this.accessLevelDescription = accessLevelDescription;
        return this;
    }

    /**
     * Getter for <code>user_for_admin.created_at</code>. 创建时间
     */
    @Override
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>user_for_admin.created_at</code>. 创建时间
     */
    @Override
    public UserForAdmin setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>user_for_admin.phone</code>. 电话号
     */
    @Override
    public Long getPhone() {
        return this.phone;
    }

    /**
     * Setter for <code>user_for_admin.phone</code>. 电话号
     */
    @Override
    public UserForAdmin setPhone(Long phone) {
        this.phone = phone;
        return this;
    }

    /**
     * Getter for <code>user_for_admin.money</code>. 可用钱数（单位为分）
     */
    @Override
    public Integer getMoney() {
        return this.money;
    }

    /**
     * Setter for <code>user_for_admin.money</code>. 可用钱数（单位为分）
     */
    @Override
    public UserForAdmin setMoney(Integer money) {
        this.money = money;
        return this;
    }

    /**
     * Getter for <code>user_for_admin.card_serial_id</code>. 卡片序列号
     */
    @Override
    public Long getCardSerialId() {
        return this.cardSerialId;
    }

    /**
     * Setter for <code>user_for_admin.card_serial_id</code>. 卡片序列号
     */
    @Override
    public UserForAdmin setCardSerialId(Long cardSerialId) {
        this.cardSerialId = cardSerialId;
        return this;
    }

    /**
     * Getter for <code>user_for_admin.start_year</code>. 入学(职)年份
     */
    @Override
    public Short getStartYear() {
        return this.startYear;
    }

    /**
     * Setter for <code>user_for_admin.start_year</code>. 入学(职)年份
     */
    @Override
    public UserForAdmin setStartYear(Short startYear) {
        this.startYear = startYear;
        return this;
    }

    /**
     * Getter for <code>user_for_admin.department</code>. 所在部门
     */
    @Override
    public String getDepartment() {
        return this.department;
    }

    /**
     * Setter for <code>user_for_admin.department</code>. 所在部门
     */
    @Override
    public UserForAdmin setDepartment(String department) {
        this.department = department;
        return this;
    }

    /**
     * Getter for <code>user_for_admin.comment</code>. 备注
     */
    @Override
    public String getComment() {
        return this.comment;
    }

    /**
     * Setter for <code>user_for_admin.comment</code>. 备注
     */
    @Override
    public UserForAdmin setComment(String comment) {
        this.comment = comment;
        return this;
    }

    /**
     * Getter for <code>user_for_admin.ip_creation</code>. 创建时IP
     */
    @Override
    public String getIpCreation() {
        return this.ipCreation;
    }

    /**
     * Setter for <code>user_for_admin.ip_creation</code>. 创建时IP
     */
    @Override
    public UserForAdmin setIpCreation(String ipCreation) {
        this.ipCreation = ipCreation;
        return this;
    }

    /**
     * Getter for <code>user_for_admin.ip_login</code>. 上次登录IP
     */
    @Override
    public String getIpLogin() {
        return this.ipLogin;
    }

    /**
     * Setter for <code>user_for_admin.ip_login</code>. 上次登录IP
     */
    @Override
    public UserForAdmin setIpLogin(String ipLogin) {
        this.ipLogin = ipLogin;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserForAdmin (");

        sb.append(uid);
        sb.append(", ").append(serialId);
        sb.append(", ").append(email);
        sb.append(", ").append(realName);
        sb.append(", ").append(password);
        sb.append(", ").append(accessLevel);
        sb.append(", ").append(accessLevelDescription);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(phone);
        sb.append(", ").append(money);
        sb.append(", ").append(cardSerialId);
        sb.append(", ").append(startYear);
        sb.append(", ").append(department);
        sb.append(", ").append(comment);
        sb.append(", ").append(ipCreation);
        sb.append(", ").append(ipLogin);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUserForAdmin from) {
        setUid(from.getUid());
        setSerialId(from.getSerialId());
        setEmail(from.getEmail());
        setRealName(from.getRealName());
        setPassword(from.getPassword());
        setAccessLevel(from.getAccessLevel());
        setAccessLevelDescription(from.getAccessLevelDescription());
        setCreatedAt(from.getCreatedAt());
        setPhone(from.getPhone());
        setMoney(from.getMoney());
        setCardSerialId(from.getCardSerialId());
        setStartYear(from.getStartYear());
        setDepartment(from.getDepartment());
        setComment(from.getComment());
        setIpCreation(from.getIpCreation());
        setIpLogin(from.getIpLogin());
    }

    @Override
    public <E extends IUserForAdmin> E into(E into) {
        into.from(this);
        return into;
    }
}
