/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.pojos;


import com.kenvix.bookmgr.orm.tables.interfaces.IUserAccessLevel;

import javax.annotation.processing.Generated;


/**
 * 用户访问级别定义
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAccessLevel implements IUserAccessLevel {

    private static final long serialVersionUID = -1926023378;

    private Byte   id;
    private String description;

    public UserAccessLevel() {}

    public UserAccessLevel(IUserAccessLevel value) {
        this.id = value.getId();
        this.description = value.getDescription();
    }

    public UserAccessLevel(
        Byte   id,
        String description
    ) {
        this.id = id;
        this.description = description;
    }

    @Override
    public Byte getId() {
        return this.id;
    }

    @Override
    public UserAccessLevel setId(Byte id) {
        this.id = id;
        return this;
    }

    @Override
    public String getDescription() {
        return this.description;
    }

    @Override
    public UserAccessLevel setDescription(String description) {
        this.description = description;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserAccessLevel (");

        sb.append(id);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUserAccessLevel from) {
        setId(from.getId());
        setDescription(from.getDescription());
    }

    @Override
    public <E extends IUserAccessLevel> E into(E into) {
        into.from(this);
        return into;
    }
}
