/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.records;


import com.kenvix.bookmgr.orm.tables.Book;
import com.kenvix.bookmgr.orm.tables.interfaces.IBook;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 书籍表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookRecord extends UpdatableRecordImpl<BookRecord> implements Record11<Long, Long, Integer, String, String, Long, Timestamp, Integer, Integer, String, Byte>, IBook {

    private static final long serialVersionUID = -385837608;

    /**
     * Setter for <code>book.id</code>. 书本ID
     */
    @Override
    public BookRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>book.id</code>. 书本ID
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>book.creator_uid</code>. 条目创建者UID
     */
    @Override
    public BookRecord setCreatorUid(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>book.creator_uid</code>. 条目创建者UID
     */
    @Override
    public Long getCreatorUid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>book.type_id</code>. 图书类型ID
     */
    @Override
    public BookRecord setTypeId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>book.type_id</code>. 图书类型ID
     */
    @Override
    public Integer getTypeId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>book.title</code>. 书籍标题
     */
    @Override
    public BookRecord setTitle(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>book.title</code>. 书籍标题
     */
    @Override
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>book.description</code>. 书籍概述
     */
    @Override
    public BookRecord setDescription(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>book.description</code>. 书籍概述
     */
    @Override
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>book.publisher_id</code>. 出版社ID
     */
    @Override
    public BookRecord setPublisherId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>book.publisher_id</code>. 出版社ID
     */
    @Override
    public Long getPublisherId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>book.created_at</code>. 条目创建时间
     */
    @Override
    public BookRecord setCreatedAt(Timestamp value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>book.created_at</code>. 条目创建时间
     */
    @Override
    public Timestamp getCreatedAt() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>book.num_total</code>. 书籍总数
     */
    @Override
    public BookRecord setNumTotal(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>book.num_total</code>. 书籍总数
     */
    @Override
    public Integer getNumTotal() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>book.num_available</code>. 可用书籍数
     */
    @Override
    public BookRecord setNumAvailable(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>book.num_available</code>. 可用书籍数
     */
    @Override
    public Integer getNumAvailable() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>book.isbn</code>. 国际标准书号 (International Standard Book Number)
     */
    @Override
    public BookRecord setIsbn(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>book.isbn</code>. 国际标准书号 (International Standard Book Number)
     */
    @Override
    public String getIsbn() {
        return (String) get(9);
    }

    /**
     * Setter for <code>book.status</code>. 书籍状态
     */
    @Override
    public BookRecord setStatus(Byte value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>book.status</code>. 书籍状态
     */
    @Override
    public Byte getStatus() {
        return (Byte) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, Long, Integer, String, String, Long, Timestamp, Integer, Integer, String, Byte> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, Long, Integer, String, String, Long, Timestamp, Integer, Integer, String, Byte> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Book.BOOK.ID;
    }

    @Override
    public Field<Long> field2() {
        return Book.BOOK.CREATOR_UID;
    }

    @Override
    public Field<Integer> field3() {
        return Book.BOOK.TYPE_ID;
    }

    @Override
    public Field<String> field4() {
        return Book.BOOK.TITLE;
    }

    @Override
    public Field<String> field5() {
        return Book.BOOK.DESCRIPTION;
    }

    @Override
    public Field<Long> field6() {
        return Book.BOOK.PUBLISHER_ID;
    }

    @Override
    public Field<Timestamp> field7() {
        return Book.BOOK.CREATED_AT;
    }

    @Override
    public Field<Integer> field8() {
        return Book.BOOK.NUM_TOTAL;
    }

    @Override
    public Field<Integer> field9() {
        return Book.BOOK.NUM_AVAILABLE;
    }

    @Override
    public Field<String> field10() {
        return Book.BOOK.ISBN;
    }

    @Override
    public Field<Byte> field11() {
        return Book.BOOK.STATUS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCreatorUid();
    }

    @Override
    public Integer component3() {
        return getTypeId();
    }

    @Override
    public String component4() {
        return getTitle();
    }

    @Override
    public String component5() {
        return getDescription();
    }

    @Override
    public Long component6() {
        return getPublisherId();
    }

    @Override
    public Timestamp component7() {
        return getCreatedAt();
    }

    @Override
    public Integer component8() {
        return getNumTotal();
    }

    @Override
    public Integer component9() {
        return getNumAvailable();
    }

    @Override
    public String component10() {
        return getIsbn();
    }

    @Override
    public Byte component11() {
        return getStatus();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCreatorUid();
    }

    @Override
    public Integer value3() {
        return getTypeId();
    }

    @Override
    public String value4() {
        return getTitle();
    }

    @Override
    public String value5() {
        return getDescription();
    }

    @Override
    public Long value6() {
        return getPublisherId();
    }

    @Override
    public Timestamp value7() {
        return getCreatedAt();
    }

    @Override
    public Integer value8() {
        return getNumTotal();
    }

    @Override
    public Integer value9() {
        return getNumAvailable();
    }

    @Override
    public String value10() {
        return getIsbn();
    }

    @Override
    public Byte value11() {
        return getStatus();
    }

    @Override
    public BookRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public BookRecord value2(Long value) {
        setCreatorUid(value);
        return this;
    }

    @Override
    public BookRecord value3(Integer value) {
        setTypeId(value);
        return this;
    }

    @Override
    public BookRecord value4(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public BookRecord value5(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public BookRecord value6(Long value) {
        setPublisherId(value);
        return this;
    }

    @Override
    public BookRecord value7(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public BookRecord value8(Integer value) {
        setNumTotal(value);
        return this;
    }

    @Override
    public BookRecord value9(Integer value) {
        setNumAvailable(value);
        return this;
    }

    @Override
    public BookRecord value10(String value) {
        setIsbn(value);
        return this;
    }

    @Override
    public BookRecord value11(Byte value) {
        setStatus(value);
        return this;
    }

    @Override
    public BookRecord values(Long value1, Long value2, Integer value3, String value4, String value5, Long value6, Timestamp value7, Integer value8, Integer value9, String value10, Byte value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IBook from) {
        setId(from.getId());
        setCreatorUid(from.getCreatorUid());
        setTypeId(from.getTypeId());
        setTitle(from.getTitle());
        setDescription(from.getDescription());
        setPublisherId(from.getPublisherId());
        setCreatedAt(from.getCreatedAt());
        setNumTotal(from.getNumTotal());
        setNumAvailable(from.getNumAvailable());
        setIsbn(from.getIsbn());
        setStatus(from.getStatus());
    }

    @Override
    public <E extends IBook> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookRecord
     */
    public BookRecord() {
        super(Book.BOOK);
    }

    /**
     * Create a detached, initialised BookRecord
     */
    public BookRecord(Long id, Long creatorUid, Integer typeId, String title, String description, Long publisherId, Timestamp createdAt, Integer numTotal, Integer numAvailable, String isbn, Byte status) {
        super(Book.BOOK);

        set(0, id);
        set(1, creatorUid);
        set(2, typeId);
        set(3, title);
        set(4, description);
        set(5, publisherId);
        set(6, createdAt);
        set(7, numTotal);
        set(8, numAvailable);
        set(9, isbn);
        set(10, status);
    }
}
