/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.records;


import com.kenvix.bookmgr.orm.tables.BookBorrow;
import com.kenvix.bookmgr.orm.tables.interfaces.IBookBorrow;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 借书表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookBorrowRecord extends UpdatableRecordImpl<BookBorrowRecord> implements Record6<Long, Long, Long, Timestamp, Timestamp, Timestamp>, IBookBorrow {

    private static final long serialVersionUID = -1064536016;

    /**
     * Setter for <code>book_borrow.id</code>.
     */
    @Override
    public BookBorrowRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>book_borrow.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>book_borrow.book_id</code>. 书籍ID
     */
    @Override
    public BookBorrowRecord setBookId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>book_borrow.book_id</code>. 书籍ID
     */
    @Override
    public Long getBookId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>book_borrow.borrower_uid</code>. 借书人UID
     */
    @Override
    public BookBorrowRecord setBorrowerUid(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>book_borrow.borrower_uid</code>. 借书人UID
     */
    @Override
    public Long getBorrowerUid() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>book_borrow.borrowed_at</code>. 借书日期
     */
    @Override
    public BookBorrowRecord setBorrowedAt(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>book_borrow.borrowed_at</code>. 借书日期
     */
    @Override
    public Timestamp getBorrowedAt() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>book_borrow.expected_returned_at</code>. 期望的还书日期
     */
    @Override
    public BookBorrowRecord setExpectedReturnedAt(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>book_borrow.expected_returned_at</code>. 期望的还书日期
     */
    @Override
    public Timestamp getExpectedReturnedAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>book_borrow.actual_returned_at</code>. 实际还书日期，NULL为没还
     */
    @Override
    public BookBorrowRecord setActualReturnedAt(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>book_borrow.actual_returned_at</code>. 实际还书日期，NULL为没还
     */
    @Override
    public Timestamp getActualReturnedAt() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, Timestamp, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Long, Timestamp, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return BookBorrow.BOOK_BORROW.ID;
    }

    @Override
    public Field<Long> field2() {
        return BookBorrow.BOOK_BORROW.BOOK_ID;
    }

    @Override
    public Field<Long> field3() {
        return BookBorrow.BOOK_BORROW.BORROWER_UID;
    }

    @Override
    public Field<Timestamp> field4() {
        return BookBorrow.BOOK_BORROW.BORROWED_AT;
    }

    @Override
    public Field<Timestamp> field5() {
        return BookBorrow.BOOK_BORROW.EXPECTED_RETURNED_AT;
    }

    @Override
    public Field<Timestamp> field6() {
        return BookBorrow.BOOK_BORROW.ACTUAL_RETURNED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getBookId();
    }

    @Override
    public Long component3() {
        return getBorrowerUid();
    }

    @Override
    public Timestamp component4() {
        return getBorrowedAt();
    }

    @Override
    public Timestamp component5() {
        return getExpectedReturnedAt();
    }

    @Override
    public Timestamp component6() {
        return getActualReturnedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getBookId();
    }

    @Override
    public Long value3() {
        return getBorrowerUid();
    }

    @Override
    public Timestamp value4() {
        return getBorrowedAt();
    }

    @Override
    public Timestamp value5() {
        return getExpectedReturnedAt();
    }

    @Override
    public Timestamp value6() {
        return getActualReturnedAt();
    }

    @Override
    public BookBorrowRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public BookBorrowRecord value2(Long value) {
        setBookId(value);
        return this;
    }

    @Override
    public BookBorrowRecord value3(Long value) {
        setBorrowerUid(value);
        return this;
    }

    @Override
    public BookBorrowRecord value4(Timestamp value) {
        setBorrowedAt(value);
        return this;
    }

    @Override
    public BookBorrowRecord value5(Timestamp value) {
        setExpectedReturnedAt(value);
        return this;
    }

    @Override
    public BookBorrowRecord value6(Timestamp value) {
        setActualReturnedAt(value);
        return this;
    }

    @Override
    public BookBorrowRecord values(Long value1, Long value2, Long value3, Timestamp value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IBookBorrow from) {
        setId(from.getId());
        setBookId(from.getBookId());
        setBorrowerUid(from.getBorrowerUid());
        setBorrowedAt(from.getBorrowedAt());
        setExpectedReturnedAt(from.getExpectedReturnedAt());
        setActualReturnedAt(from.getActualReturnedAt());
    }

    @Override
    public <E extends IBookBorrow> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookBorrowRecord
     */
    public BookBorrowRecord() {
        super(BookBorrow.BOOK_BORROW);
    }

    /**
     * Create a detached, initialised BookBorrowRecord
     */
    public BookBorrowRecord(Long id, Long bookId, Long borrowerUid, Timestamp borrowedAt, Timestamp expectedReturnedAt, Timestamp actualReturnedAt) {
        super(BookBorrow.BOOK_BORROW);

        set(0, id);
        set(1, bookId);
        set(2, borrowerUid);
        set(3, borrowedAt);
        set(4, expectedReturnedAt);
        set(5, actualReturnedAt);
    }
}
