/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.records;


import com.kenvix.bookmgr.orm.tables.BookBorrowExpired;
import com.kenvix.bookmgr.orm.tables.interfaces.IBookBorrowExpired;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookBorrowExpiredRecord extends TableRecordImpl<BookBorrowExpiredRecord> implements Record8<Long, Long, Timestamp, Timestamp, String, String, String, String>, IBookBorrowExpired {

    private static final long serialVersionUID = -1197065718;

    /**
     * Setter for <code>book_borrow_expired.book_id</code>. 书籍ID
     */
    @Override
    public BookBorrowExpiredRecord setBookId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>book_borrow_expired.book_id</code>. 书籍ID
     */
    @Override
    public Long getBookId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>book_borrow_expired.borrower_uid</code>. 借书人UID
     */
    @Override
    public BookBorrowExpiredRecord setBorrowerUid(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>book_borrow_expired.borrower_uid</code>. 借书人UID
     */
    @Override
    public Long getBorrowerUid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>book_borrow_expired.borrowed_at</code>. 借书日期
     */
    @Override
    public BookBorrowExpiredRecord setBorrowedAt(Timestamp value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>book_borrow_expired.borrowed_at</code>. 借书日期
     */
    @Override
    public Timestamp getBorrowedAt() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>book_borrow_expired.expected_returned_at</code>. 期望的还书日期
     */
    @Override
    public BookBorrowExpiredRecord setExpectedReturnedAt(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>book_borrow_expired.expected_returned_at</code>. 期望的还书日期
     */
    @Override
    public Timestamp getExpectedReturnedAt() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>book_borrow_expired.book_title</code>. 书籍标题
     */
    @Override
    public BookBorrowExpiredRecord setBookTitle(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>book_borrow_expired.book_title</code>. 书籍标题
     */
    @Override
    public String getBookTitle() {
        return (String) get(4);
    }

    /**
     * Setter for <code>book_borrow_expired.borrower_email</code>. 电子邮箱
     */
    @Override
    public BookBorrowExpiredRecord setBorrowerEmail(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>book_borrow_expired.borrower_email</code>. 电子邮箱
     */
    @Override
    public String getBorrowerEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>book_borrow_expired.borrower_real_name</code>. 真实姓名
     */
    @Override
    public BookBorrowExpiredRecord setBorrowerRealName(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>book_borrow_expired.borrower_real_name</code>. 真实姓名
     */
    @Override
    public String getBorrowerRealName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>book_borrow_expired.borrower_serial_id</code>. 工号/序列号
     */
    @Override
    public BookBorrowExpiredRecord setBorrowerSerialId(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>book_borrow_expired.borrower_serial_id</code>. 工号/序列号
     */
    @Override
    public String getBorrowerSerialId() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Long, Timestamp, Timestamp, String, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Long, Timestamp, Timestamp, String, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return BookBorrowExpired.BOOK_BORROW_EXPIRED.BOOK_ID;
    }

    @Override
    public Field<Long> field2() {
        return BookBorrowExpired.BOOK_BORROW_EXPIRED.BORROWER_UID;
    }

    @Override
    public Field<Timestamp> field3() {
        return BookBorrowExpired.BOOK_BORROW_EXPIRED.BORROWED_AT;
    }

    @Override
    public Field<Timestamp> field4() {
        return BookBorrowExpired.BOOK_BORROW_EXPIRED.EXPECTED_RETURNED_AT;
    }

    @Override
    public Field<String> field5() {
        return BookBorrowExpired.BOOK_BORROW_EXPIRED.BOOK_TITLE;
    }

    @Override
    public Field<String> field6() {
        return BookBorrowExpired.BOOK_BORROW_EXPIRED.BORROWER_EMAIL;
    }

    @Override
    public Field<String> field7() {
        return BookBorrowExpired.BOOK_BORROW_EXPIRED.BORROWER_REAL_NAME;
    }

    @Override
    public Field<String> field8() {
        return BookBorrowExpired.BOOK_BORROW_EXPIRED.BORROWER_SERIAL_ID;
    }

    @Override
    public Long component1() {
        return getBookId();
    }

    @Override
    public Long component2() {
        return getBorrowerUid();
    }

    @Override
    public Timestamp component3() {
        return getBorrowedAt();
    }

    @Override
    public Timestamp component4() {
        return getExpectedReturnedAt();
    }

    @Override
    public String component5() {
        return getBookTitle();
    }

    @Override
    public String component6() {
        return getBorrowerEmail();
    }

    @Override
    public String component7() {
        return getBorrowerRealName();
    }

    @Override
    public String component8() {
        return getBorrowerSerialId();
    }

    @Override
    public Long value1() {
        return getBookId();
    }

    @Override
    public Long value2() {
        return getBorrowerUid();
    }

    @Override
    public Timestamp value3() {
        return getBorrowedAt();
    }

    @Override
    public Timestamp value4() {
        return getExpectedReturnedAt();
    }

    @Override
    public String value5() {
        return getBookTitle();
    }

    @Override
    public String value6() {
        return getBorrowerEmail();
    }

    @Override
    public String value7() {
        return getBorrowerRealName();
    }

    @Override
    public String value8() {
        return getBorrowerSerialId();
    }

    @Override
    public BookBorrowExpiredRecord value1(Long value) {
        setBookId(value);
        return this;
    }

    @Override
    public BookBorrowExpiredRecord value2(Long value) {
        setBorrowerUid(value);
        return this;
    }

    @Override
    public BookBorrowExpiredRecord value3(Timestamp value) {
        setBorrowedAt(value);
        return this;
    }

    @Override
    public BookBorrowExpiredRecord value4(Timestamp value) {
        setExpectedReturnedAt(value);
        return this;
    }

    @Override
    public BookBorrowExpiredRecord value5(String value) {
        setBookTitle(value);
        return this;
    }

    @Override
    public BookBorrowExpiredRecord value6(String value) {
        setBorrowerEmail(value);
        return this;
    }

    @Override
    public BookBorrowExpiredRecord value7(String value) {
        setBorrowerRealName(value);
        return this;
    }

    @Override
    public BookBorrowExpiredRecord value8(String value) {
        setBorrowerSerialId(value);
        return this;
    }

    @Override
    public BookBorrowExpiredRecord values(Long value1, Long value2, Timestamp value3, Timestamp value4, String value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IBookBorrowExpired from) {
        setBookId(from.getBookId());
        setBorrowerUid(from.getBorrowerUid());
        setBorrowedAt(from.getBorrowedAt());
        setExpectedReturnedAt(from.getExpectedReturnedAt());
        setBookTitle(from.getBookTitle());
        setBorrowerEmail(from.getBorrowerEmail());
        setBorrowerRealName(from.getBorrowerRealName());
        setBorrowerSerialId(from.getBorrowerSerialId());
    }

    @Override
    public <E extends IBookBorrowExpired> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookBorrowExpiredRecord
     */
    public BookBorrowExpiredRecord() {
        super(BookBorrowExpired.BOOK_BORROW_EXPIRED);
    }

    /**
     * Create a detached, initialised BookBorrowExpiredRecord
     */
    public BookBorrowExpiredRecord(Long bookId, Long borrowerUid, Timestamp borrowedAt, Timestamp expectedReturnedAt, String bookTitle, String borrowerEmail, String borrowerRealName, String borrowerSerialId) {
        super(BookBorrowExpired.BOOK_BORROW_EXPIRED);

        set(0, bookId);
        set(1, borrowerUid);
        set(2, borrowedAt);
        set(3, expectedReturnedAt);
        set(4, bookTitle);
        set(5, borrowerEmail);
        set(6, borrowerRealName);
        set(7, borrowerSerialId);
    }
}
