/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.records;


import com.kenvix.bookmgr.orm.tables.BookBorrowForAdmin;
import com.kenvix.bookmgr.orm.tables.interfaces.IBookBorrowForAdmin;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookBorrowForAdminRecord extends TableRecordImpl<BookBorrowForAdminRecord> implements Record8<Long, String, Long, Timestamp, Timestamp, Timestamp, String, String>, IBookBorrowForAdmin {

    private static final long serialVersionUID = -2036439157;

    /**
     * Setter for <code>book_borrow_for_admin.book_id</code>. 书籍ID
     */
    @Override
    public BookBorrowForAdminRecord setBookId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>book_borrow_for_admin.book_id</code>. 书籍ID
     */
    @Override
    public Long getBookId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>book_borrow_for_admin.book_title</code>. 书籍标题
     */
    @Override
    public BookBorrowForAdminRecord setBookTitle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>book_borrow_for_admin.book_title</code>. 书籍标题
     */
    @Override
    public String getBookTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>book_borrow_for_admin.borrower_uid</code>. 借书人UID
     */
    @Override
    public BookBorrowForAdminRecord setBorrowerUid(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>book_borrow_for_admin.borrower_uid</code>. 借书人UID
     */
    @Override
    public Long getBorrowerUid() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>book_borrow_for_admin.borrowed_at</code>. 借书日期
     */
    @Override
    public BookBorrowForAdminRecord setBorrowedAt(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>book_borrow_for_admin.borrowed_at</code>. 借书日期
     */
    @Override
    public Timestamp getBorrowedAt() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>book_borrow_for_admin.expected_returned_at</code>. 期望的还书日期
     */
    @Override
    public BookBorrowForAdminRecord setExpectedReturnedAt(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>book_borrow_for_admin.expected_returned_at</code>. 期望的还书日期
     */
    @Override
    public Timestamp getExpectedReturnedAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>book_borrow_for_admin.actual_returned_at</code>. 实际还书日期，NULL为没还
     */
    @Override
    public BookBorrowForAdminRecord setActualReturnedAt(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>book_borrow_for_admin.actual_returned_at</code>. 实际还书日期，NULL为没还
     */
    @Override
    public Timestamp getActualReturnedAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>book_borrow_for_admin.borrower_real_name</code>. 真实姓名
     */
    @Override
    public BookBorrowForAdminRecord setBorrowerRealName(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>book_borrow_for_admin.borrower_real_name</code>. 真实姓名
     */
    @Override
    public String getBorrowerRealName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>book_borrow_for_admin.borrower_serial_id</code>. 工号/序列号
     */
    @Override
    public BookBorrowForAdminRecord setBorrowerSerialId(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>book_borrow_for_admin.borrower_serial_id</code>. 工号/序列号
     */
    @Override
    public String getBorrowerSerialId() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, Long, Timestamp, Timestamp, Timestamp, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, String, Long, Timestamp, Timestamp, Timestamp, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return BookBorrowForAdmin.BOOK_BORROW_FOR_ADMIN.BOOK_ID;
    }

    @Override
    public Field<String> field2() {
        return BookBorrowForAdmin.BOOK_BORROW_FOR_ADMIN.BOOK_TITLE;
    }

    @Override
    public Field<Long> field3() {
        return BookBorrowForAdmin.BOOK_BORROW_FOR_ADMIN.BORROWER_UID;
    }

    @Override
    public Field<Timestamp> field4() {
        return BookBorrowForAdmin.BOOK_BORROW_FOR_ADMIN.BORROWED_AT;
    }

    @Override
    public Field<Timestamp> field5() {
        return BookBorrowForAdmin.BOOK_BORROW_FOR_ADMIN.EXPECTED_RETURNED_AT;
    }

    @Override
    public Field<Timestamp> field6() {
        return BookBorrowForAdmin.BOOK_BORROW_FOR_ADMIN.ACTUAL_RETURNED_AT;
    }

    @Override
    public Field<String> field7() {
        return BookBorrowForAdmin.BOOK_BORROW_FOR_ADMIN.BORROWER_REAL_NAME;
    }

    @Override
    public Field<String> field8() {
        return BookBorrowForAdmin.BOOK_BORROW_FOR_ADMIN.BORROWER_SERIAL_ID;
    }

    @Override
    public Long component1() {
        return getBookId();
    }

    @Override
    public String component2() {
        return getBookTitle();
    }

    @Override
    public Long component3() {
        return getBorrowerUid();
    }

    @Override
    public Timestamp component4() {
        return getBorrowedAt();
    }

    @Override
    public Timestamp component5() {
        return getExpectedReturnedAt();
    }

    @Override
    public Timestamp component6() {
        return getActualReturnedAt();
    }

    @Override
    public String component7() {
        return getBorrowerRealName();
    }

    @Override
    public String component8() {
        return getBorrowerSerialId();
    }

    @Override
    public Long value1() {
        return getBookId();
    }

    @Override
    public String value2() {
        return getBookTitle();
    }

    @Override
    public Long value3() {
        return getBorrowerUid();
    }

    @Override
    public Timestamp value4() {
        return getBorrowedAt();
    }

    @Override
    public Timestamp value5() {
        return getExpectedReturnedAt();
    }

    @Override
    public Timestamp value6() {
        return getActualReturnedAt();
    }

    @Override
    public String value7() {
        return getBorrowerRealName();
    }

    @Override
    public String value8() {
        return getBorrowerSerialId();
    }

    @Override
    public BookBorrowForAdminRecord value1(Long value) {
        setBookId(value);
        return this;
    }

    @Override
    public BookBorrowForAdminRecord value2(String value) {
        setBookTitle(value);
        return this;
    }

    @Override
    public BookBorrowForAdminRecord value3(Long value) {
        setBorrowerUid(value);
        return this;
    }

    @Override
    public BookBorrowForAdminRecord value4(Timestamp value) {
        setBorrowedAt(value);
        return this;
    }

    @Override
    public BookBorrowForAdminRecord value5(Timestamp value) {
        setExpectedReturnedAt(value);
        return this;
    }

    @Override
    public BookBorrowForAdminRecord value6(Timestamp value) {
        setActualReturnedAt(value);
        return this;
    }

    @Override
    public BookBorrowForAdminRecord value7(String value) {
        setBorrowerRealName(value);
        return this;
    }

    @Override
    public BookBorrowForAdminRecord value8(String value) {
        setBorrowerSerialId(value);
        return this;
    }

    @Override
    public BookBorrowForAdminRecord values(Long value1, String value2, Long value3, Timestamp value4, Timestamp value5, Timestamp value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IBookBorrowForAdmin from) {
        setBookId(from.getBookId());
        setBookTitle(from.getBookTitle());
        setBorrowerUid(from.getBorrowerUid());
        setBorrowedAt(from.getBorrowedAt());
        setExpectedReturnedAt(from.getExpectedReturnedAt());
        setActualReturnedAt(from.getActualReturnedAt());
        setBorrowerRealName(from.getBorrowerRealName());
        setBorrowerSerialId(from.getBorrowerSerialId());
    }

    @Override
    public <E extends IBookBorrowForAdmin> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookBorrowForAdminRecord
     */
    public BookBorrowForAdminRecord() {
        super(BookBorrowForAdmin.BOOK_BORROW_FOR_ADMIN);
    }

    /**
     * Create a detached, initialised BookBorrowForAdminRecord
     */
    public BookBorrowForAdminRecord(Long bookId, String bookTitle, Long borrowerUid, Timestamp borrowedAt, Timestamp expectedReturnedAt, Timestamp actualReturnedAt, String borrowerRealName, String borrowerSerialId) {
        super(BookBorrowForAdmin.BOOK_BORROW_FOR_ADMIN);

        set(0, bookId);
        set(1, bookTitle);
        set(2, borrowerUid);
        set(3, borrowedAt);
        set(4, expectedReturnedAt);
        set(5, actualReturnedAt);
        set(6, borrowerRealName);
        set(7, borrowerSerialId);
    }
}
