/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.records;


import com.kenvix.bookmgr.orm.tables.LogCardAccessForAdmin;
import com.kenvix.bookmgr.orm.tables.interfaces.ILogCardAccessForAdmin;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LogCardAccessForAdminRecord extends TableRecordImpl<LogCardAccessForAdminRecord> implements Record7<Long, Long, Long, Timestamp, Integer, String, String>, ILogCardAccessForAdmin {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>log_card_access_for_admin.serial_id</code>. 卡序列号
     */
    @Override
    public LogCardAccessForAdminRecord setSerialId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>log_card_access_for_admin.serial_id</code>. 卡序列号
     */
    @Override
    public Long getSerialId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>log_card_access_for_admin.card_serial_id</code>. 卡片序列号
     */
    @Override
    public LogCardAccessForAdminRecord setCardSerialId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>log_card_access_for_admin.card_serial_id</code>. 卡片序列号
     */
    @Override
    public Long getCardSerialId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>log_card_access_for_admin.uid</code>. 用户UID
     */
    @Override
    public LogCardAccessForAdminRecord setUid(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>log_card_access_for_admin.uid</code>. 用户UID
     */
    @Override
    public Long getUid() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>log_card_access_for_admin.time</code>. 刷卡时间
     */
    @Override
    public LogCardAccessForAdminRecord setTime(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>log_card_access_for_admin.time</code>. 刷卡时间
     */
    @Override
    public Timestamp getTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>log_card_access_for_admin.machine_id</code>. 刷卡机器编号
     */
    @Override
    public LogCardAccessForAdminRecord setMachineId(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>log_card_access_for_admin.machine_id</code>. 刷卡机器编号
     */
    @Override
    public Integer getMachineId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>log_card_access_for_admin.email</code>. 电子邮箱
     */
    @Override
    public LogCardAccessForAdminRecord setEmail(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>log_card_access_for_admin.email</code>. 电子邮箱
     */
    @Override
    public String getEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>log_card_access_for_admin.real_name</code>. 真实姓名
     */
    @Override
    public LogCardAccessForAdminRecord setRealName(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>log_card_access_for_admin.real_name</code>. 真实姓名
     */
    @Override
    public String getRealName() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, Long, Timestamp, Integer, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, Long, Timestamp, Integer, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return LogCardAccessForAdmin.LOG_CARD_ACCESS_FOR_ADMIN.SERIAL_ID;
    }

    @Override
    public Field<Long> field2() {
        return LogCardAccessForAdmin.LOG_CARD_ACCESS_FOR_ADMIN.CARD_SERIAL_ID;
    }

    @Override
    public Field<Long> field3() {
        return LogCardAccessForAdmin.LOG_CARD_ACCESS_FOR_ADMIN.UID;
    }

    @Override
    public Field<Timestamp> field4() {
        return LogCardAccessForAdmin.LOG_CARD_ACCESS_FOR_ADMIN.TIME;
    }

    @Override
    public Field<Integer> field5() {
        return LogCardAccessForAdmin.LOG_CARD_ACCESS_FOR_ADMIN.MACHINE_ID;
    }

    @Override
    public Field<String> field6() {
        return LogCardAccessForAdmin.LOG_CARD_ACCESS_FOR_ADMIN.EMAIL;
    }

    @Override
    public Field<String> field7() {
        return LogCardAccessForAdmin.LOG_CARD_ACCESS_FOR_ADMIN.REAL_NAME;
    }

    @Override
    public Long component1() {
        return getSerialId();
    }

    @Override
    public Long component2() {
        return getCardSerialId();
    }

    @Override
    public Long component3() {
        return getUid();
    }

    @Override
    public Timestamp component4() {
        return getTime();
    }

    @Override
    public Integer component5() {
        return getMachineId();
    }

    @Override
    public String component6() {
        return getEmail();
    }

    @Override
    public String component7() {
        return getRealName();
    }

    @Override
    public Long value1() {
        return getSerialId();
    }

    @Override
    public Long value2() {
        return getCardSerialId();
    }

    @Override
    public Long value3() {
        return getUid();
    }

    @Override
    public Timestamp value4() {
        return getTime();
    }

    @Override
    public Integer value5() {
        return getMachineId();
    }

    @Override
    public String value6() {
        return getEmail();
    }

    @Override
    public String value7() {
        return getRealName();
    }

    @Override
    public LogCardAccessForAdminRecord value1(Long value) {
        setSerialId(value);
        return this;
    }

    @Override
    public LogCardAccessForAdminRecord value2(Long value) {
        setCardSerialId(value);
        return this;
    }

    @Override
    public LogCardAccessForAdminRecord value3(Long value) {
        setUid(value);
        return this;
    }

    @Override
    public LogCardAccessForAdminRecord value4(Timestamp value) {
        setTime(value);
        return this;
    }

    @Override
    public LogCardAccessForAdminRecord value5(Integer value) {
        setMachineId(value);
        return this;
    }

    @Override
    public LogCardAccessForAdminRecord value6(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public LogCardAccessForAdminRecord value7(String value) {
        setRealName(value);
        return this;
    }

    @Override
    public LogCardAccessForAdminRecord values(Long value1, Long value2, Long value3, Timestamp value4, Integer value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ILogCardAccessForAdmin from) {
        setSerialId(from.getSerialId());
        setCardSerialId(from.getCardSerialId());
        setUid(from.getUid());
        setTime(from.getTime());
        setMachineId(from.getMachineId());
        setEmail(from.getEmail());
        setRealName(from.getRealName());
    }

    @Override
    public <E extends ILogCardAccessForAdmin> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LogCardAccessForAdminRecord
     */
    public LogCardAccessForAdminRecord() {
        super(LogCardAccessForAdmin.LOG_CARD_ACCESS_FOR_ADMIN);
    }

    /**
     * Create a detached, initialised LogCardAccessForAdminRecord
     */
    public LogCardAccessForAdminRecord(Long serialId, Long cardSerialId, Long uid, Timestamp time, Integer machineId, String email, String realName) {
        super(LogCardAccessForAdmin.LOG_CARD_ACCESS_FOR_ADMIN);

        setSerialId(serialId);
        setCardSerialId(cardSerialId);
        setUid(uid);
        setTime(time);
        setMachineId(machineId);
        setEmail(email);
        setRealName(realName);
    }
}
