/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.records;


import com.kenvix.bookmgr.orm.tables.UserForAdmin;
import com.kenvix.bookmgr.orm.tables.interfaces.IUserForAdmin;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserForAdminRecord extends TableRecordImpl<UserForAdminRecord> implements Record16<Long, String, String, String, String, Byte, String, Timestamp, Long, Integer, Long, Short, String, String, String, String>, IUserForAdmin {

    private static final long serialVersionUID = 348405433;

    /**
     * Setter for <code>user_for_admin.uid</code>. 用户UID
     */
    @Override
    public UserForAdminRecord setUid(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>user_for_admin.uid</code>. 用户UID
     */
    @Override
    public Long getUid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>user_for_admin.serial_id</code>. 工号/序列号
     */
    @Override
    public UserForAdminRecord setSerialId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>user_for_admin.serial_id</code>. 工号/序列号
     */
    @Override
    public String getSerialId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>user_for_admin.email</code>. 电子邮箱
     */
    @Override
    public UserForAdminRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>user_for_admin.email</code>. 电子邮箱
     */
    @Override
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>user_for_admin.real_name</code>. 真实姓名
     */
    @Override
    public UserForAdminRecord setRealName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>user_for_admin.real_name</code>. 真实姓名
     */
    @Override
    public String getRealName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>user_for_admin.password</code>. Bcrypt密码哈希值
     */
    @Override
    public UserForAdminRecord setPassword(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>user_for_admin.password</code>. Bcrypt密码哈希值
     */
    @Override
    public String getPassword() {
        return (String) get(4);
    }

    /**
     * Setter for <code>user_for_admin.access_level</code>. 访问级别
     */
    @Override
    public UserForAdminRecord setAccessLevel(Byte value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>user_for_admin.access_level</code>. 访问级别
     */
    @Override
    public Byte getAccessLevel() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>user_for_admin.access_level_description</code>.
     */
    @Override
    public UserForAdminRecord setAccessLevelDescription(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>user_for_admin.access_level_description</code>.
     */
    @Override
    public String getAccessLevelDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>user_for_admin.created_at</code>. 创建时间
     */
    @Override
    public UserForAdminRecord setCreatedAt(Timestamp value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>user_for_admin.created_at</code>. 创建时间
     */
    @Override
    public Timestamp getCreatedAt() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>user_for_admin.phone</code>. 电话号
     */
    @Override
    public UserForAdminRecord setPhone(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>user_for_admin.phone</code>. 电话号
     */
    @Override
    public Long getPhone() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>user_for_admin.money</code>. 可用钱数（单位为分）
     */
    @Override
    public UserForAdminRecord setMoney(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>user_for_admin.money</code>. 可用钱数（单位为分）
     */
    @Override
    public Integer getMoney() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>user_for_admin.card_serial_id</code>. 卡片序列号
     */
    @Override
    public UserForAdminRecord setCardSerialId(Long value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>user_for_admin.card_serial_id</code>. 卡片序列号
     */
    @Override
    public Long getCardSerialId() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>user_for_admin.start_year</code>. 入学(职)年份
     */
    @Override
    public UserForAdminRecord setStartYear(Short value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>user_for_admin.start_year</code>. 入学(职)年份
     */
    @Override
    public Short getStartYear() {
        return (Short) get(11);
    }

    /**
     * Setter for <code>user_for_admin.department</code>. 所在部门
     */
    @Override
    public UserForAdminRecord setDepartment(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>user_for_admin.department</code>. 所在部门
     */
    @Override
    public String getDepartment() {
        return (String) get(12);
    }

    /**
     * Setter for <code>user_for_admin.comment</code>. 备注
     */
    @Override
    public UserForAdminRecord setComment(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>user_for_admin.comment</code>. 备注
     */
    @Override
    public String getComment() {
        return (String) get(13);
    }

    /**
     * Setter for <code>user_for_admin.ip_creation</code>. 创建时IP
     */
    @Override
    public UserForAdminRecord setIpCreation(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>user_for_admin.ip_creation</code>. 创建时IP
     */
    @Override
    public String getIpCreation() {
        return (String) get(14);
    }

    /**
     * Setter for <code>user_for_admin.ip_login</code>. 上次登录IP
     */
    @Override
    public UserForAdminRecord setIpLogin(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>user_for_admin.ip_login</code>. 上次登录IP
     */
    @Override
    public String getIpLogin() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<Long, String, String, String, String, Byte, String, Timestamp, Long, Integer, Long, Short, String, String, String, String> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<Long, String, String, String, String, Byte, String, Timestamp, Long, Integer, Long, Short, String, String, String, String> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserForAdmin.USER_FOR_ADMIN.UID;
    }

    @Override
    public Field<String> field2() {
        return UserForAdmin.USER_FOR_ADMIN.SERIAL_ID;
    }

    @Override
    public Field<String> field3() {
        return UserForAdmin.USER_FOR_ADMIN.EMAIL;
    }

    @Override
    public Field<String> field4() {
        return UserForAdmin.USER_FOR_ADMIN.REAL_NAME;
    }

    @Override
    public Field<String> field5() {
        return UserForAdmin.USER_FOR_ADMIN.PASSWORD;
    }

    @Override
    public Field<Byte> field6() {
        return UserForAdmin.USER_FOR_ADMIN.ACCESS_LEVEL;
    }

    @Override
    public Field<String> field7() {
        return UserForAdmin.USER_FOR_ADMIN.ACCESS_LEVEL_DESCRIPTION;
    }

    @Override
    public Field<Timestamp> field8() {
        return UserForAdmin.USER_FOR_ADMIN.CREATED_AT;
    }

    @Override
    public Field<Long> field9() {
        return UserForAdmin.USER_FOR_ADMIN.PHONE;
    }

    @Override
    public Field<Integer> field10() {
        return UserForAdmin.USER_FOR_ADMIN.MONEY;
    }

    @Override
    public Field<Long> field11() {
        return UserForAdmin.USER_FOR_ADMIN.CARD_SERIAL_ID;
    }

    @Override
    public Field<Short> field12() {
        return UserForAdmin.USER_FOR_ADMIN.START_YEAR;
    }

    @Override
    public Field<String> field13() {
        return UserForAdmin.USER_FOR_ADMIN.DEPARTMENT;
    }

    @Override
    public Field<String> field14() {
        return UserForAdmin.USER_FOR_ADMIN.COMMENT;
    }

    @Override
    public Field<String> field15() {
        return UserForAdmin.USER_FOR_ADMIN.IP_CREATION;
    }

    @Override
    public Field<String> field16() {
        return UserForAdmin.USER_FOR_ADMIN.IP_LOGIN;
    }

    @Override
    public Long component1() {
        return getUid();
    }

    @Override
    public String component2() {
        return getSerialId();
    }

    @Override
    public String component3() {
        return getEmail();
    }

    @Override
    public String component4() {
        return getRealName();
    }

    @Override
    public String component5() {
        return getPassword();
    }

    @Override
    public Byte component6() {
        return getAccessLevel();
    }

    @Override
    public String component7() {
        return getAccessLevelDescription();
    }

    @Override
    public Timestamp component8() {
        return getCreatedAt();
    }

    @Override
    public Long component9() {
        return getPhone();
    }

    @Override
    public Integer component10() {
        return getMoney();
    }

    @Override
    public Long component11() {
        return getCardSerialId();
    }

    @Override
    public Short component12() {
        return getStartYear();
    }

    @Override
    public String component13() {
        return getDepartment();
    }

    @Override
    public String component14() {
        return getComment();
    }

    @Override
    public String component15() {
        return getIpCreation();
    }

    @Override
    public String component16() {
        return getIpLogin();
    }

    @Override
    public Long value1() {
        return getUid();
    }

    @Override
    public String value2() {
        return getSerialId();
    }

    @Override
    public String value3() {
        return getEmail();
    }

    @Override
    public String value4() {
        return getRealName();
    }

    @Override
    public String value5() {
        return getPassword();
    }

    @Override
    public Byte value6() {
        return getAccessLevel();
    }

    @Override
    public String value7() {
        return getAccessLevelDescription();
    }

    @Override
    public Timestamp value8() {
        return getCreatedAt();
    }

    @Override
    public Long value9() {
        return getPhone();
    }

    @Override
    public Integer value10() {
        return getMoney();
    }

    @Override
    public Long value11() {
        return getCardSerialId();
    }

    @Override
    public Short value12() {
        return getStartYear();
    }

    @Override
    public String value13() {
        return getDepartment();
    }

    @Override
    public String value14() {
        return getComment();
    }

    @Override
    public String value15() {
        return getIpCreation();
    }

    @Override
    public String value16() {
        return getIpLogin();
    }

    @Override
    public UserForAdminRecord value1(Long value) {
        setUid(value);
        return this;
    }

    @Override
    public UserForAdminRecord value2(String value) {
        setSerialId(value);
        return this;
    }

    @Override
    public UserForAdminRecord value3(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UserForAdminRecord value4(String value) {
        setRealName(value);
        return this;
    }

    @Override
    public UserForAdminRecord value5(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UserForAdminRecord value6(Byte value) {
        setAccessLevel(value);
        return this;
    }

    @Override
    public UserForAdminRecord value7(String value) {
        setAccessLevelDescription(value);
        return this;
    }

    @Override
    public UserForAdminRecord value8(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public UserForAdminRecord value9(Long value) {
        setPhone(value);
        return this;
    }

    @Override
    public UserForAdminRecord value10(Integer value) {
        setMoney(value);
        return this;
    }

    @Override
    public UserForAdminRecord value11(Long value) {
        setCardSerialId(value);
        return this;
    }

    @Override
    public UserForAdminRecord value12(Short value) {
        setStartYear(value);
        return this;
    }

    @Override
    public UserForAdminRecord value13(String value) {
        setDepartment(value);
        return this;
    }

    @Override
    public UserForAdminRecord value14(String value) {
        setComment(value);
        return this;
    }

    @Override
    public UserForAdminRecord value15(String value) {
        setIpCreation(value);
        return this;
    }

    @Override
    public UserForAdminRecord value16(String value) {
        setIpLogin(value);
        return this;
    }

    @Override
    public UserForAdminRecord values(Long value1, String value2, String value3, String value4, String value5, Byte value6, String value7, Timestamp value8, Long value9, Integer value10, Long value11, Short value12, String value13, String value14, String value15, String value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUserForAdmin from) {
        setUid(from.getUid());
        setSerialId(from.getSerialId());
        setEmail(from.getEmail());
        setRealName(from.getRealName());
        setPassword(from.getPassword());
        setAccessLevel(from.getAccessLevel());
        setAccessLevelDescription(from.getAccessLevelDescription());
        setCreatedAt(from.getCreatedAt());
        setPhone(from.getPhone());
        setMoney(from.getMoney());
        setCardSerialId(from.getCardSerialId());
        setStartYear(from.getStartYear());
        setDepartment(from.getDepartment());
        setComment(from.getComment());
        setIpCreation(from.getIpCreation());
        setIpLogin(from.getIpLogin());
    }

    @Override
    public <E extends IUserForAdmin> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserForAdminRecord
     */
    public UserForAdminRecord() {
        super(UserForAdmin.USER_FOR_ADMIN);
    }

    /**
     * Create a detached, initialised UserForAdminRecord
     */
    public UserForAdminRecord(Long uid, String serialId, String email, String realName, String password, Byte accessLevel, String accessLevelDescription, Timestamp createdAt, Long phone, Integer money, Long cardSerialId, Short startYear, String department, String comment, String ipCreation, String ipLogin) {
        super(UserForAdmin.USER_FOR_ADMIN);

        set(0, uid);
        set(1, serialId);
        set(2, email);
        set(3, realName);
        set(4, password);
        set(5, accessLevel);
        set(6, accessLevelDescription);
        set(7, createdAt);
        set(8, phone);
        set(9, money);
        set(10, cardSerialId);
        set(11, startYear);
        set(12, department);
        set(13, comment);
        set(14, ipCreation);
        set(15, ipLogin);
    }
}
