/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;


/**
 * VIEW
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IBookBorrowForAdmin extends Serializable {

    /**
     * Setter for <code>book_borrow_for_admin.book_id</code>. 书籍ID
     */
    public IBookBorrowForAdmin setBookId(Long value);

    /**
     * Getter for <code>book_borrow_for_admin.book_id</code>. 书籍ID
     */
    public Long getBookId();

    /**
     * Setter for <code>book_borrow_for_admin.book_title</code>. 书籍标题
     */
    public IBookBorrowForAdmin setBookTitle(String value);

    /**
     * Getter for <code>book_borrow_for_admin.book_title</code>. 书籍标题
     */
    public String getBookTitle();

    /**
     * Setter for <code>book_borrow_for_admin.borrower_uid</code>. 借书人UID
     */
    public IBookBorrowForAdmin setBorrowerUid(Long value);

    /**
     * Getter for <code>book_borrow_for_admin.borrower_uid</code>. 借书人UID
     */
    public Long getBorrowerUid();

    /**
     * Setter for <code>book_borrow_for_admin.borrowed_at</code>. 借书日期
     */
    public IBookBorrowForAdmin setBorrowedAt(Timestamp value);

    /**
     * Getter for <code>book_borrow_for_admin.borrowed_at</code>. 借书日期
     */
    public Timestamp getBorrowedAt();

    /**
     * Setter for <code>book_borrow_for_admin.expected_returned_at</code>. 期望的还书日期
     */
    public IBookBorrowForAdmin setExpectedReturnedAt(Timestamp value);

    /**
     * Getter for <code>book_borrow_for_admin.expected_returned_at</code>. 期望的还书日期
     */
    public Timestamp getExpectedReturnedAt();

    /**
     * Setter for <code>book_borrow_for_admin.actual_returned_at</code>. 实际还书日期，NULL为没还
     */
    public IBookBorrowForAdmin setActualReturnedAt(Timestamp value);

    /**
     * Getter for <code>book_borrow_for_admin.actual_returned_at</code>. 实际还书日期，NULL为没还
     */
    public Timestamp getActualReturnedAt();

    /**
     * Setter for <code>book_borrow_for_admin.borrower_real_name</code>. 真实姓名
     */
    public IBookBorrowForAdmin setBorrowerRealName(String value);

    /**
     * Getter for <code>book_borrow_for_admin.borrower_real_name</code>. 真实姓名
     */
    public String getBorrowerRealName();

    /**
     * Setter for <code>book_borrow_for_admin.borrower_serial_id</code>. 工号/序列号
     */
    public IBookBorrowForAdmin setBorrowerSerialId(String value);

    /**
     * Getter for <code>book_borrow_for_admin.borrower_serial_id</code>. 工号/序列号
     */
    public String getBorrowerSerialId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IBookBorrowForAdmin
     */
    public void from(IBookBorrowForAdmin from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IBookBorrowForAdmin
     */
    public <E extends IBookBorrowForAdmin> E into(E into);
}
