/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.interfaces;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * 图书类目
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IBookType extends Serializable {

    /**
     * Setter for <code>book_type.id</code>. 图书类目ID
     */
    public IBookType setId(Integer value);

    /**
     * Getter for <code>book_type.id</code>. 图书类目ID
     */
    public Integer getId();

    /**
     * Setter for <code>book_type.name</code>. 类目名称
     */
    public IBookType setName(String value);

    /**
     * Getter for <code>book_type.name</code>. 类目名称
     */
    public String getName();

    /**
     * Setter for <code>book_type.parent_id</code>. 父级图书类目ID
     */
    public IBookType setParentId(Integer value);

    /**
     * Getter for <code>book_type.parent_id</code>. 父级图书类目ID
     */
    public Integer getParentId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IBookType
     */
    public void from(IBookType from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IBookType
     */
    public <E extends IBookType> E into(E into);
}
