/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.interfaces;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * 订单状态
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IInvoiceStatus extends Serializable {

    /**
     * Setter for <code>invoice_status.id</code>.
     */
    public IInvoiceStatus setId(Byte value);

    /**
     * Getter for <code>invoice_status.id</code>.
     */
    public Byte getId();

    /**
     * Setter for <code>invoice_status.description</code>.
     */
    public IInvoiceStatus setDescription(String value);

    /**
     * Getter for <code>invoice_status.description</code>.
     */
    public String getDescription();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IInvoiceStatus
     */
    public void from(IInvoiceStatus from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IInvoiceStatus
     */
    public <E extends IInvoiceStatus> E into(E into);
}
