/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.JSON;


/**
 * VIEW
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IInvoiceForUser extends Serializable {

    /**
     * Setter for <code>invoice_for_user.id</code>. 订单ID
     */
    public IInvoiceForUser setId(Long value);

    /**
     * Getter for <code>invoice_for_user.id</code>. 订单ID
     */
    public Long getId();

    /**
     * Setter for <code>invoice_for_user.name</code>. 订单名称
     */
    public IInvoiceForUser setName(String value);

    /**
     * Getter for <code>invoice_for_user.name</code>. 订单名称
     */
    public String getName();

    /**
     * Setter for <code>invoice_for_user.type</code>. 订单类型
     */
    public IInvoiceForUser setType(Short value);

    /**
     * Getter for <code>invoice_for_user.type</code>. 订单类型
     */
    public Short getType();

    /**
     * Setter for <code>invoice_for_user.owner_uid</code>. 付款人UID
     */
    public IInvoiceForUser setOwnerUid(Long value);

    /**
     * Getter for <code>invoice_for_user.owner_uid</code>. 付款人UID
     */
    public Long getOwnerUid();

    /**
     * Setter for <code>invoice_for_user.should_pay</code>. 应付金额
     */
    public IInvoiceForUser setShouldPay(Integer value);

    /**
     * Getter for <code>invoice_for_user.should_pay</code>. 应付金额
     */
    public Integer getShouldPay();

    /**
     * Setter for <code>invoice_for_user.created_at</code>. 创建时间
     */
    public IInvoiceForUser setCreatedAt(Timestamp value);

    /**
     * Getter for <code>invoice_for_user.created_at</code>. 创建时间
     */
    public Timestamp getCreatedAt();

    /**
     * Setter for <code>invoice_for_user.status</code>. 订单状态
     */
    public IInvoiceForUser setStatus(Byte value);

    /**
     * Getter for <code>invoice_for_user.status</code>. 订单状态
     */
    public Byte getStatus();

    /**
     * Setter for <code>invoice_for_user.status_description</code>.
     */
    public IInvoiceForUser setStatusDescription(String value);

    /**
     * Getter for <code>invoice_for_user.status_description</code>.
     */
    public String getStatusDescription();

    /**
     * Setter for <code>invoice_for_user.expire_at</code>. 订单过期时间
     */
    public IInvoiceForUser setExpireAt(Timestamp value);

    /**
     * Getter for <code>invoice_for_user.expire_at</code>. 订单过期时间
     */
    public Timestamp getExpireAt();

    /**
     * Setter for <code>invoice_for_user.paid_at</code>. 订单支付时间,NULL为没付
     */
    public IInvoiceForUser setPaidAt(Timestamp value);

    /**
     * Getter for <code>invoice_for_user.paid_at</code>. 订单支付时间,NULL为没付
     */
    public Timestamp getPaidAt();

    /**
     * Setter for <code>invoice_for_user.comment</code>. 订单备注
     */
    public IInvoiceForUser setComment(String value);

    /**
     * Getter for <code>invoice_for_user.comment</code>. 订单备注
     */
    public String getComment();

    /**
     * Setter for <code>invoice_for_user.extra_data</code>. 保留备用。特定订单驱动可读的数据信息
     */
    public IInvoiceForUser setExtraData(JSON value);

    /**
     * Getter for <code>invoice_for_user.extra_data</code>. 保留备用。特定订单驱动可读的数据信息
     */
    public JSON getExtraData();

    /**
     * Setter for <code>invoice_for_user.type_description</code>.
     */
    public IInvoiceForUser setTypeDescription(String value);

    /**
     * Getter for <code>invoice_for_user.type_description</code>.
     */
    public String getTypeDescription();

    /**
     * Setter for <code>invoice_for_user.type_driver</code>.
     */
    public IInvoiceForUser setTypeDriver(String value);

    /**
     * Getter for <code>invoice_for_user.type_driver</code>.
     */
    public String getTypeDriver();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IInvoiceForUser
     */
    public void from(IInvoiceForUser from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IInvoiceForUser
     */
    public <E extends IInvoiceForUser> E into(E into);
}
