/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.JSON;


/**
 * 账单，包括罚款
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IInvoice extends Serializable {

    /**
     * Setter for <code>invoice.id</code>. 订单ID
     */
    public IInvoice setId(Long value);

    /**
     * Getter for <code>invoice.id</code>. 订单ID
     */
    public Long getId();

    /**
     * Setter for <code>invoice.name</code>. 订单名称
     */
    public IInvoice setName(String value);

    /**
     * Getter for <code>invoice.name</code>. 订单名称
     */
    public String getName();

    /**
     * Setter for <code>invoice.type</code>. 订单类型
     */
    public IInvoice setType(Short value);

    /**
     * Getter for <code>invoice.type</code>. 订单类型
     */
    public Short getType();

    /**
     * Setter for <code>invoice.owner_uid</code>. 付款人UID
     */
    public IInvoice setOwnerUid(Long value);

    /**
     * Getter for <code>invoice.owner_uid</code>. 付款人UID
     */
    public Long getOwnerUid();

    /**
     * Setter for <code>invoice.should_pay</code>. 应付金额
     */
    public IInvoice setShouldPay(Integer value);

    /**
     * Getter for <code>invoice.should_pay</code>. 应付金额
     */
    public Integer getShouldPay();

    /**
     * Setter for <code>invoice.created_at</code>. 创建时间
     */
    public IInvoice setCreatedAt(Timestamp value);

    /**
     * Getter for <code>invoice.created_at</code>. 创建时间
     */
    public Timestamp getCreatedAt();

    /**
     * Setter for <code>invoice.status</code>. 订单状态
     */
    public IInvoice setStatus(Byte value);

    /**
     * Getter for <code>invoice.status</code>. 订单状态
     */
    public Byte getStatus();

    /**
     * Setter for <code>invoice.expire_at</code>. 订单过期时间
     */
    public IInvoice setExpireAt(Timestamp value);

    /**
     * Getter for <code>invoice.expire_at</code>. 订单过期时间
     */
    public Timestamp getExpireAt();

    /**
     * Setter for <code>invoice.paid_at</code>. 订单支付时间,NULL为没付
     */
    public IInvoice setPaidAt(Timestamp value);

    /**
     * Getter for <code>invoice.paid_at</code>. 订单支付时间,NULL为没付
     */
    public Timestamp getPaidAt();

    /**
     * Setter for <code>invoice.comment</code>. 订单备注
     */
    public IInvoice setComment(String value);

    /**
     * Getter for <code>invoice.comment</code>. 订单备注
     */
    public String getComment();

    /**
     * Setter for <code>invoice.extra_data</code>. 保留备用。特定订单驱动可读的数据信息
     */
    public IInvoice setExtraData(JSON value);

    /**
     * Getter for <code>invoice.extra_data</code>. 保留备用。特定订单驱动可读的数据信息
     */
    public JSON getExtraData();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IInvoice
     */
    public void from(IInvoice from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IInvoice
     */
    public <E extends IInvoice> E into(E into);
}
