/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;


/**
 * VIEW
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ILogCardAccessForAdmin extends Serializable {

    /**
     * Setter for <code>log_card_access_for_admin.serial_id</code>. 卡序列号
     */
    public ILogCardAccessForAdmin setSerialId(Long value);

    /**
     * Getter for <code>log_card_access_for_admin.serial_id</code>. 卡序列号
     */
    public Long getSerialId();

    /**
     * Setter for <code>log_card_access_for_admin.card_serial_id</code>. 卡片序列号
     */
    public ILogCardAccessForAdmin setCardSerialId(Long value);

    /**
     * Getter for <code>log_card_access_for_admin.card_serial_id</code>. 卡片序列号
     */
    public Long getCardSerialId();

    /**
     * Setter for <code>log_card_access_for_admin.uid</code>. 用户UID
     */
    public ILogCardAccessForAdmin setUid(Long value);

    /**
     * Getter for <code>log_card_access_for_admin.uid</code>. 用户UID
     */
    public Long getUid();

    /**
     * Setter for <code>log_card_access_for_admin.time</code>. 刷卡时间
     */
    public ILogCardAccessForAdmin setTime(Timestamp value);

    /**
     * Getter for <code>log_card_access_for_admin.time</code>. 刷卡时间
     */
    public Timestamp getTime();

    /**
     * Setter for <code>log_card_access_for_admin.machine_id</code>. 刷卡机器编号
     */
    public ILogCardAccessForAdmin setMachineId(Integer value);

    /**
     * Getter for <code>log_card_access_for_admin.machine_id</code>. 刷卡机器编号
     */
    public Integer getMachineId();

    /**
     * Setter for <code>log_card_access_for_admin.email</code>. 电子邮箱
     */
    public ILogCardAccessForAdmin setEmail(String value);

    /**
     * Getter for <code>log_card_access_for_admin.email</code>. 电子邮箱
     */
    public String getEmail();

    /**
     * Setter for <code>log_card_access_for_admin.real_name</code>. 真实姓名
     */
    public ILogCardAccessForAdmin setRealName(String value);

    /**
     * Getter for <code>log_card_access_for_admin.real_name</code>. 真实姓名
     */
    public String getRealName();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ILogCardAccessForAdmin
     */
    public void from(ILogCardAccessForAdmin from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ILogCardAccessForAdmin
     */
    public <E extends ILogCardAccessForAdmin> E into(E into);
}
