/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.interfaces;


import com.kenvix.bookmgr.orm.enums.LogSystemLevel;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;


/**
 * 系统日志
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ILogSystem extends Serializable {

    /**
     * Setter for <code>log_system.id</code>.
     */
    public ILogSystem setId(Long value);

    /**
     * Getter for <code>log_system.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>log_system.source</code>. 日志来源
     */
    public ILogSystem setSource(String value);

    /**
     * Getter for <code>log_system.source</code>. 日志来源
     */
    public String getSource();

    /**
     * Setter for <code>log_system.level</code>. 日志级别
     */
    public ILogSystem setLevel(LogSystemLevel value);

    /**
     * Getter for <code>log_system.level</code>. 日志级别
     */
    public LogSystemLevel getLevel();

    /**
     * Setter for <code>log_system.time</code>. 发生事件
     */
    public ILogSystem setTime(Timestamp value);

    /**
     * Getter for <code>log_system.time</code>. 发生事件
     */
    public Timestamp getTime();

    /**
     * Setter for <code>log_system.message</code>. 消息
     */
    public ILogSystem setMessage(String value);

    /**
     * Getter for <code>log_system.message</code>. 消息
     */
    public String getMessage();

    /**
     * Setter for <code>log_system.exception</code>. 日志异常类型（简化名）
     */
    public ILogSystem setException(String value);

    /**
     * Getter for <code>log_system.exception</code>. 日志异常类型（简化名）
     */
    public String getException();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ILogSystem
     */
    public void from(ILogSystem from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ILogSystem
     */
    public <E extends ILogSystem> E into(E into);
}
