/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;


/**
 * 用户登录日志（不可修改和删除）
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ILogUserLogin extends Serializable {

    /**
     * Setter for <code>log_user_login.id</code>.
     */
    public ILogUserLogin setId(Long value);

    /**
     * Getter for <code>log_user_login.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>log_user_login.uid</code>. 用户UID
     */
    public ILogUserLogin setUid(Long value);

    /**
     * Getter for <code>log_user_login.uid</code>. 用户UID
     */
    public Long getUid();

    /**
     * Setter for <code>log_user_login.time</code>. 登录时间
     */
    public ILogUserLogin setTime(Timestamp value);

    /**
     * Getter for <code>log_user_login.time</code>. 登录时间
     */
    public Timestamp getTime();

    /**
     * Setter for <code>log_user_login.ip</code>. 登录IP
     */
    public ILogUserLogin setIp(String value);

    /**
     * Getter for <code>log_user_login.ip</code>. 登录IP
     */
    public String getIp();

    /**
     * Setter for <code>log_user_login.useragent</code>. 用户代理
     */
    public ILogUserLogin setUseragent(String value);

    /**
     * Getter for <code>log_user_login.useragent</code>. 用户代理
     */
    public String getUseragent();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ILogUserLogin
     */
    public void from(ILogUserLogin from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ILogUserLogin
     */
    public <E extends ILogUserLogin> E into(E into);
}
