/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.JSON;


/**
 * 任务队列（程序可读）
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITaskQueue extends Serializable {

    /**
     * Setter for <code>task_queue.id</code>.
     */
    public ITaskQueue setId(Long value);

    /**
     * Getter for <code>task_queue.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>task_queue.created_at</code>.
     */
    public ITaskQueue setCreatedAt(Timestamp value);

    /**
     * Getter for <code>task_queue.created_at</code>.
     */
    public Timestamp getCreatedAt();

    /**
     * Setter for <code>task_queue.finished_at</code>.
     */
    public ITaskQueue setFinishedAt(Timestamp value);

    /**
     * Getter for <code>task_queue.finished_at</code>.
     */
    public Timestamp getFinishedAt();

    /**
     * Setter for <code>task_queue.is_finished</code>.
     */
    public ITaskQueue setIsFinished(Boolean value);

    /**
     * Getter for <code>task_queue.is_finished</code>.
     */
    public Boolean getIsFinished();

    /**
     * Setter for <code>task_queue.is_success</code>.
     */
    public ITaskQueue setIsSuccess(Boolean value);

    /**
     * Getter for <code>task_queue.is_success</code>.
     */
    public Boolean getIsSuccess();

    /**
     * Setter for <code>task_queue.is_doing</code>.
     */
    public ITaskQueue setIsDoing(Boolean value);

    /**
     * Getter for <code>task_queue.is_doing</code>.
     */
    public Boolean getIsDoing();

    /**
     * Setter for <code>task_queue.type</code>.
     */
    public ITaskQueue setType(Short value);

    /**
     * Getter for <code>task_queue.type</code>.
     */
    public Short getType();

    /**
     * Setter for <code>task_queue.content</code>. 任务正文（程序可读）
     */
    public ITaskQueue setContent(JSON value);

    /**
     * Getter for <code>task_queue.content</code>. 任务正文（程序可读）
     */
    public JSON getContent();

    /**
     * Setter for <code>task_queue.result</code>. 任务结果（程序可读）
     */
    public ITaskQueue setResult(JSON value);

    /**
     * Getter for <code>task_queue.result</code>. 任务结果（程序可读）
     */
    public JSON getResult();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITaskQueue
     */
    public void from(ITaskQueue from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITaskQueue
     */
    public <E extends ITaskQueue> E into(E into);
}
