/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.interfaces;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * 用户扩展信息
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUserExtra extends Serializable {

    /**
     * Setter for <code>user_extra.uid</code>.
     */
    public IUserExtra setUid(Long value);

    /**
     * Getter for <code>user_extra.uid</code>.
     */
    public Long getUid();

    /**
     * Setter for <code>user_extra.phone</code>. 电话号
     */
    public IUserExtra setPhone(Long value);

    /**
     * Getter for <code>user_extra.phone</code>. 电话号
     */
    public Long getPhone();

    /**
     * Setter for <code>user_extra.card_serial_id</code>. 卡片序列号
     */
    public IUserExtra setCardSerialId(Long value);

    /**
     * Getter for <code>user_extra.card_serial_id</code>. 卡片序列号
     */
    public Long getCardSerialId();

    /**
     * Setter for <code>user_extra.start_year</code>. 入学(职)年份
     */
    public IUserExtra setStartYear(Short value);

    /**
     * Getter for <code>user_extra.start_year</code>. 入学(职)年份
     */
    public Short getStartYear();

    /**
     * Setter for <code>user_extra.department</code>. 所在部门
     */
    public IUserExtra setDepartment(String value);

    /**
     * Getter for <code>user_extra.department</code>. 所在部门
     */
    public String getDepartment();

    /**
     * Setter for <code>user_extra.comment</code>. 备注
     */
    public IUserExtra setComment(String value);

    /**
     * Getter for <code>user_extra.comment</code>. 备注
     */
    public String getComment();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IUserExtra
     */
    public void from(IUserExtra from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IUserExtra
     */
    public <E extends IUserExtra> E into(E into);
}
