/*
 * This file is generated by jOOQ.
 */
package com.kenvix.bookmgr.orm.tables.interfaces;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * 用户访问级别定义
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUserAccessLevel extends Serializable {

    /**
     * Setter for <code>user_access_level.id</code>.
     */
    public IUserAccessLevel setId(Byte value);

    /**
     * Getter for <code>user_access_level.id</code>.
     */
    public Byte getId();

    /**
     * Setter for <code>user_access_level.description</code>.
     */
    public IUserAccessLevel setDescription(String value);

    /**
     * Getter for <code>user_access_level.description</code>.
     */
    public String getDescription();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IUserAccessLevel
     */
    public void from(IUserAccessLevel from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IUserAccessLevel
     */
    public <E extends IUserAccessLevel> E into(E into);
}
